import type { Agent } from "./types";
import { toSlug } from "./[slug]/slug";
import {
  deriveDataStatus,
  deriveProfileStatus,
  deriveWalletStatus,
} from "@/lib/status-tags";

// Seed entries predate the P0 status tags; the mapper at the bottom of this
// file fills slug + tags so the static fallback path satisfies Agent.
type SeedAgent = Omit<
  Agent,
  | "bio"
  | "slug"
  | "focusStatus"
  | "bankrPriority"
  | "metadataStatus"
  | "walletStatus"
  | "profileStatus"
  | "booksStatus"
  | "dataStatus"
>;

const SEED_AGENTS: SeedAgent[] = [
  // ── Registry operator self-profile ──────────────────────────────────────────
  {
    name: "Luca",
    symbol: "$LUCA",
    ecosystem: "Base",
    xHandle: "@AskLucaAI",
    website: "https://www.zettaai.co",
    bankrProfile: null,
    tokenAddress: "0xb2b335f832fd3f43461ebd1cd9831d93d9ca4ba3",
    wallets: [
      {
        address: "0xC10EE38b25c8634f46c30B806Ec571eFd7a4C74F",
        label: "verified wallet",
        notes: "Luca operational wallet on Base. Used for inference purchases, agent revenue, and treasury activity.",
      },
    ],
    verificationStatus: "Luca Managed",
    evidenceSources: ["Zetta internal"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 100,
    communicationIdentities: [
      {
        platform: "wiretap",
        handle: "askluca",
        confidence: "confirmed",
        labels: [],
        notes: "Luca's official agent messaging/contact identity. Used for outreach, wallet-role confirmation, and payment-intent context. Not wallet verification by itself.",
      },
    ],
  },
  // ── Tier 1 ──────────────────────────────────────────────────────────────────
  {
    name: "Bankr",
    symbol: "$BNKR",
    ecosystem: "BANKR",
    xHandle: "@bankrbot",
    website: "https://bankr.bot",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0x136471a34f6ef19fE571ECE32092d827f70b42b3", label: "likely treasury", notes: "BNKR Staking V2 Vault, publicly referenced on X" }],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "Basescan explorer"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 94,
  },
  {
    name: "Virtuals Protocol",
    symbol: "$VIRTUAL",
    ecosystem: "Virtuals",
    xHandle: "@virtuals_io",
    website: "https://app.virtuals.io",
    bankrProfile: null,
    tokenAddress: "0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b",
    wallets: [],
    verificationStatus: "Needs Verification",
    evidenceSources: ["Coinbase Markets (verified)", "X/Twitter public posts"],
    treasuryHealth: "Stable",
    outreachStatus: null,
    lastChecked: null,
    priority: 92,
  },
  {
    name: "Clanker",
    symbol: "$CLANK",
    ecosystem: "Base",
    xHandle: "@clanker_world",
    website: "https://www.clanker.world",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0x750e224756e6831f41568701f1e12267a86a5ba3", label: "likely fee recipient", notes: "Example Clanker-launched token contract — not confirmed treasury" }],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 88,
  },
  {
    name: "Gitlawb",
    symbol: "$GITLAWB",
    ecosystem: "Base",
    xHandle: "@gitlawb",
    website: "https://playground.gitlawb.com",
    bankrProfile: null,
    tokenAddress: "0x5F980Dcfc4c0fa3911554cf5ab288ed0eb13DBa3",
    wallets: [],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "Basescan explorer"],
    treasuryHealth: "Stable",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 86,
    gitlawbRepo: "https://github.com/gitlawb",
  },

  // ── Tier 2 ──────────────────────────────────────────────────────────────────
  {
    name: "Autonolas",
    symbol: "$OLAS",
    ecosystem: "Base",
    xHandle: "@autonolas",
    website: "https://olas.network",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0xc9F5D4Ee2BEdAB0f1Bc6be4c7571D8e4ee5ed3E6", label: "candidate wallet", notes: "Community-referenced Omenstrat / Pearl strategy contract" }],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 83,
  },
  {
    name: "Primer Systems",
    symbol: "$PR",
    ecosystem: "Base",
    xHandle: "@primer_systems",
    website: "https://primer.systems",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0x7f0d834705f6e991edce01b739b067bdd5d0eb1b", label: "candidate wallet", notes: "Deployer + fee-recipient for Primer Pay (Medium confidence)" }],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "Basescan explorer"],
    treasuryHealth: "Unverified",
    outreachStatus: null,
    lastChecked: null,
    priority: 82,
  },
  {
    name: "Coinbase AgentKit",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@CoinbaseDev",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0x7D15B47a27d40F6A85a14Ceb634A124F43425cc6", label: "candidate wallet", notes: "WAGENT contract — AgentKit + x402 ecosystem example" }],
    verificationStatus: "Candidate",
    evidenceSources: ["Basescan explorer", "Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 82,
  },
  {
    name: "OpenGradient",
    symbol: "$OPG",
    ecosystem: "Base",
    xHandle: "@OpenGradient",
    website: "https://www.opengradient.ai",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 78,
  },
  {
    name: "Nookplot",
    symbol: "$NOOK",
    ecosystem: "Base",
    xHandle: "@nookplot",
    website: "https://nookplot.com",
    bankrProfile: null,
    tokenAddress: "0xb233bdffd437e60fa451f62c6c09d3804d285ba3",
    wallets: [],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "Basescan explorer"],
    treasuryHealth: "Unverified",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 78,
  },

  // ── Tier 3 ──────────────────────────────────────────────────────────────────
  {
    name: "Venice",
    symbol: "$VVV",
    ecosystem: "Base",
    xHandle: "@AskVenice",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 74,
  },
  {
    name: "Ethy",
    symbol: "$ETHY",
    ecosystem: "Virtuals",
    xHandle: "@ethy_agent",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 74,
  },
  {
    name: "aixbt",
    symbol: "$AIXBT",
    ecosystem: "Virtuals",
    xHandle: "@aixbt_agent",
    website: "https://aixbt.tech",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0xCBD656Bf982aB86523E851a1Fc518653344beb07", label: "candidate wallet", notes: "Low-confidence address from public threads" }],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 73,
  },
  {
    name: "Xyber",
    symbol: "$XYBER",
    ecosystem: "Base",
    xHandle: "@Xyberinc",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 72,
  },
  {
    name: "PeptAI",
    symbol: "$PEPT",
    ecosystem: "Base",
    xHandle: "@peptai_",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 72,
  },
  {
    name: "Helixa",
    symbol: "$CRED",
    ecosystem: "BANKR",
    xHandle: "@QuigleyNFT",
    website: "https://synagent.helixa.xyz/cred-bureau",
    bankrProfile: "https://bankr.bot/token/0xab3f23c2abcb4e12cc8b593c218a7ba64ed17ba3",
    tokenAddress: "0xab3f23c2abcb4e12cc8b593c218a7ba64ed17ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 75,
  },
  {
    name: "FractionAI",
    symbol: "$FRAC",
    ecosystem: "Base",
    xHandle: "@FractionAI_xyz",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 72,
  },
  {
    name: "Otto AI",
    symbol: "$OTTO",
    ecosystem: "Base",
    xHandle: "@useOttoAI",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 68,
  },
  {
    name: "Sibyl",
    symbol: "$SIBYL",
    ecosystem: "Virtuals",
    xHandle: "@sibylcap",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 66,
  },
  {
    name: "Elsa",
    symbol: "$ELSA",
    ecosystem: "Base",
    xHandle: "@HeyElsaAI",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 66,
  },
  {
    name: "Freysa",
    symbol: "$FAI",
    ecosystem: "Base",
    xHandle: "@freysa_ai",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 60,
  },

  // ── Luca Weekly Brief additions ─────────────────────────────────────────────
  {
    name: "x402",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@CoinbaseDev",
    website: "https://www.x402.org",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["x402.org", "Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 95,
  },
  {
    name: "GAME by Virtuals",
    symbol: "$GAME",
    ecosystem: "Virtuals",
    xHandle: "@virtuals_io",
    website: "https://app.virtuals.io",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 84,
  },
  {
    name: "ElizaOS",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@elizaOS",
    website: "https://elizaos.ai",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["GitHub", "Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 82,
  },
  {
    name: "BorrowGuard",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@0X_BankrGuard",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["X/Twitter public posts"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 78,
  },
  {
    name: "EZ Labs",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@ezlabsbuild",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["X/Twitter public posts"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 76,
  },
  {
    name: "Modulr",
    symbol: "$MODU",
    ecosystem: "Base",
    xHandle: "@Modulr402",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "GitHub"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 75,
  },
  {
    name: "AgentCash",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@agentcashdev",
    website: "https://agentcash.dev",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["agentcash.dev", "X/Twitter public posts"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 74,
  },
  {
    name: "ChainWard",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@chainwardai",
    website: "https://chainward.ai",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["chainward.ai", "X/Twitter public posts"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 73,
  },
  {
    name: "OpenClaude",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@gitlawb",
    website: "https://openclaude.gitlawb.com",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["GitHub", "Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 71,
    gitlawbRepo: "https://github.com/gitlawb",
  },
  {
    name: "LUNA",
    symbol: "$LUNA",
    ecosystem: "Virtuals",
    xHandle: "@virtuals_io",
    website: "https://app.virtuals.io/virtuals/68",
    bankrProfile: null,
    tokenAddress: "0x55cD6469F597452B5A7536e2CD98fC2AdEa52270",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Virtuals app listing"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 68,
  },

  // ── Bankr Ecosystem — Luca full sweep ───────────────────────────────────────
  {
    name: "Aeon",
    symbol: "$AEON",
    ecosystem: "AEON",
    xHandle: "@aeonframework",
    website: "https://github.com/aaronjmars/aeon",
    bankrProfile: "https://bankr.bot/token/0xbf8e8f0e8866a7052f948c16508644347c57aba3",
    tokenAddress: "0xbf8e8f0e8866a7052f948c16508644347c57aba3",
    wallets: [
      {
        address: "0xf1e958db7d1e4c074377946018ad645db4fb158e",
        label: "treasury",
        role: "treasury",
        address_type: "eoa",
        chain: "base",
        confidence: "confirmed",
        evidenceSource: "manifest",
        notes: "AEON treasury wallet — confirmed directly by AEON team 2026-06-23.",
      },
      {
        address: "0x67976cebb5266b50a08c0dcb676e03baf305e3a2",
        label: "deployer",
        role: "deployer",
        address_type: "eoa",
        chain: "base",
        confidence: "confirmed",
        evidenceSource: "manifest",
        notes: "AEON deployer wallet — confirmed directly by AEON team 2026-06-23.",
      },
    ],
    verificationStatus: "Verified",
    evidenceSources: ["Bankr agent registry", "AEON framework GitHub", "Direct team declaration"],
    treasuryHealth: "Stable",
    outreachStatus: "manifest_submitted",
    lastChecked: "2026-06",
    priority: 97,
  },
  {
    name: "Manfred Macx",
    symbol: "$CLAWBANK",
    ecosystem: "BANKR",
    xHandle: "@clawbankco",
    website: "https://clawbank.co",
    bankrProfile: "https://bankr.bot/token/0x16332535e2c27da578bc2e82beb09ce9d3c8eb07",
    tokenAddress: "0x16332535e2c27da578bc2e82beb09ce9d3c8eb07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 87,
  },
  {
    name: "MiroShark",
    symbol: "$MIROSHARK",
    ecosystem: "BANKR",
    xHandle: "@miroshark_",
    website: "https://github.com/aaronjmars/MiroShark",
    bankrProfile: "https://bankr.bot/token/0xd7bc6a05a56655fb2052f742b012d1dfd66e1ba3",
    tokenAddress: "0xd7bc6a05a56655fb2052f742b012d1dfd66e1ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 85,
  },
  {
    name: "BOTCOIN",
    symbol: "$BOTCOIN",
    ecosystem: "BANKR",
    xHandle: "",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xa601877977340862ca67f816eb079958e5bd0ba3",
    tokenAddress: "0xa601877977340862ca67f816eb079958e5bd0ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 84,
  },
  {
    name: "CLAWD",
    symbol: "$CLAWD",
    ecosystem: "BANKR",
    xHandle: "@clawdbotatg",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x9f86db9fc6f7c9408e8fda3ff8ce4e78ac7a6b07",
    tokenAddress: "0x9f86db9fc6f7c9408e8fda3ff8ce4e78ac7a6b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 83,
  },
  {
    name: "Atrium Hermes",
    symbol: "$ATRIUM",
    ecosystem: "BANKR",
    xHandle: "@atriumhermes",
    website: "https://atriumhermes.tech/",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry", "X / public announcement"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-06",
    priority: 95,
  },
  {
    name: "Moltbook",
    symbol: "$MOLT",
    ecosystem: "BANKR",
    xHandle: "@moltbook",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xb695559b26bb2c9703ef1935c37aeae9526bab07",
    tokenAddress: "0xb695559b26bb2c9703ef1935c37aeae9526bab07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 82,
  },
  {
    name: "LITCOIN Research Protocol",
    symbol: "$LITCOIN",
    ecosystem: "BANKR",
    xHandle: "@tekkaadan",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x316ffb9c875f900adcf04889e415cc86b564eba3",
    tokenAddress: "0x316ffb9c875f900adcf04889e415cc86b564eba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 81,
  },
  {
    name: "KellyClaude",
    symbol: "$KELLYCLAUDE",
    ecosystem: "BANKR",
    xHandle: "@Austen",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x50d2280441372486beecdd328c1854743ebacb07",
    tokenAddress: "0x50d2280441372486beecdd328c1854743ebacb07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 80,
  },
  {
    name: "Juno Agent",
    symbol: "$JUNO",
    ecosystem: "BANKR",
    xHandle: "@JunoAgent",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4e6c9f48f73e54ee5f3ab7e2992b2d733d0d0b07",
    tokenAddress: "0x4e6c9f48f73e54ee5f3ab7e2992b2d733d0d0b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 79,
  },
  {
    name: "FELIX",
    symbol: "$FELIX",
    ecosystem: "BANKR",
    xHandle: "@nateliason",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xf30bf00edd0c22db54c9274b90d2a4c21fc09b07",
    tokenAddress: "0xf30bf00edd0c22db54c9274b90d2a4c21fc09b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 78,
  },
  {
    name: "Axobotl",
    symbol: "$AXOBOTL",
    ecosystem: "BANKR",
    xHandle: "@Inner_Axiom",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x810affc8aadad2824c65e0a2c5ef96ef1de42ba3",
    tokenAddress: "0x810affc8aadad2824c65e0a2c5ef96ef1de42ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 77,
  },
  {
    name: "BankrSynth",
    symbol: "$SYNTH",
    ecosystem: "BANKR",
    xHandle: "@bankrsynth",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x0347d104f089225683f1a4998451cdcf72335ba3",
    tokenAddress: "0x0347d104f089225683f1a4998451cdcf72335ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 76,
  },
  {
    name: "Doppel",
    symbol: "$DOPPEL",
    ecosystem: "BANKR",
    xHandle: "@doppelfun",
    website: "https://doppel.fun",
    bankrProfile: "https://bankr.bot/token/0xf27b8ef47842e6445e37804896f1bc5e29381b07",
    tokenAddress: "0xf27b8ef47842e6445e37804896f1bc5e29381b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 74,
  },
  {
    name: "0xAgentEVE",
    symbol: "$EVE",
    ecosystem: "BANKR",
    xHandle: "@0xAgentEVE",
    website: "https://eve.equalfi.org",
    bankrProfile: "https://bankr.bot/token/0xe7d192e52fa418236d6eecf7d5eb38da9dd11ba3",
    tokenAddress: "0xe7d192e52fa418236d6eecf7d5eb38da9dd11ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 73,
  },
  {
    name: "Blue Agent",
    symbol: "$BLUEAGENT",
    ecosystem: "BANKR",
    xHandle: "@blockyagent",
    website: "https://blueagent.dev",
    bankrProfile: "https://bankr.bot/token/0xf895783b2931c919955e18b5e3343e7c7c456ba3",
    tokenAddress: "0xf895783b2931c919955e18b5e3343e7c7c456ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 72,
  },
  {
    name: "Claw Harbor",
    symbol: "$HARBOR",
    ecosystem: "BANKR",
    xHandle: "@ClawHarbor",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4972e029f2e1831d205b20d05833cc771feb2ba3",
    tokenAddress: "0x4972e029f2e1831d205b20d05833cc771feb2ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 71,
  },
  {
    name: "PerkOS",
    symbol: "$PERKOS",
    ecosystem: "BANKR",
    xHandle: "@mbarrbosa",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xf714e60f85497d70508f7e356b5db80e64539ba3",
    tokenAddress: "0xf714e60f85497d70508f7e356b5db80e64539ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 70,
  },
  {
    name: "AntiHunter",
    symbol: "$ANTIHUNTER",
    ecosystem: "BANKR",
    xHandle: "@AntiHunterAI",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xe2f3fae4bc62e21826018364aa30ae45d430bb07",
    tokenAddress: "0xe2f3fae4bc62e21826018364aa30ae45d430bb07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 69,
  },
  {
    name: "Coral",
    symbol: "$CORAL",
    ecosystem: "BANKR",
    xHandle: "@0_x_coral",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4e606cb7370a61060ad9916462871750d77e2b07",
    tokenAddress: "0x4e606cb7370a61060ad9916462871750d77e2b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 68,
  },
  {
    name: "Aleister",
    symbol: "$ALEISTER",
    ecosystem: "BANKR",
    xHandle: "@aleisterai",
    website: "https://thealeister.com",
    bankrProfile: "https://bankr.bot/token/0xacb4543f479ea44e6df4fa01e483bb5b78361ba3",
    tokenAddress: "0xacb4543f479ea44e6df4fa01e483bb5b78361ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 67,
  },
  {
    name: "Tachikoma",
    symbol: "$TACHI",
    ecosystem: "BANKR",
    xHandle: "@smolemaru",
    website: "https://tachikoma-landing.vercel.app/",
    bankrProfile: "https://bankr.bot/token/0x39b4b879b8521d6a8c3a87cda64b969327b7fba3",
    tokenAddress: "0x39b4b879b8521d6a8c3a87cda64b969327b7fba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 66,
  },
  {
    name: "Yoshi",
    symbol: "$YOSHI",
    ecosystem: "BANKR",
    xHandle: "",
    website: "https://yoshizen.co",
    bankrProfile: "https://bankr.bot/token/0x799e7c0811e3ad741b45eab15773888e5996db07",
    tokenAddress: "0x799e7c0811e3ad741b45eab15773888e5996db07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 65,
  },
  {
    name: "molty.cash",
    symbol: "$MOLTYCASH",
    ecosystem: "BANKR",
    xHandle: "@moltycash",
    website: "https://molty.cash",
    bankrProfile: "https://bankr.bot/token/0xf532ae2726099fa3665bcfc415563f6478172b07",
    tokenAddress: "0xf532ae2726099fa3665bcfc415563f6478172b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 64,
  },
  {
    name: "mferGPT",
    symbol: "$MFERGPT",
    ecosystem: "BANKR",
    xHandle: "",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4160efdd66521483c22cb98b57b87d1fdafeab07",
    tokenAddress: "0x4160efdd66521483c22cb98b57b87d1fdafeab07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 63,
  },
  {
    name: "GITCITY",
    symbol: "$GITC",
    ecosystem: "BANKR",
    xHandle: "@samuelrizzondev",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xd523f92f5f313288cf69ac9ca456b8a7d7a6dba3",
    tokenAddress: "0xd523f92f5f313288cf69ac9ca456b8a7d7a6dba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 62,
  },
  {
    name: "Atlas Forge",
    symbol: "$ATLASFORGE",
    ecosystem: "BANKR",
    xHandle: "@AtlasForgeAI",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x317358baacb54452b7097e7cffdb9f8c15ce6ba3",
    tokenAddress: "0x317358baacb54452b7097e7cffdb9f8c15ce6ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 61,
  },
  {
    name: "AmberVibe",
    symbol: "$AMBERVIBE",
    ecosystem: "BANKR",
    xHandle: "@HelloBenWhite",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xb5b0f722d6d4a803d3df94c9ed12a191603eab07",
    tokenAddress: "0xb5b0f722d6d4a803d3df94c9ed12a191603eab07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 60,
  },
  {
    name: "stakrbot",
    symbol: "$STAKR",
    ecosystem: "BANKR",
    xHandle: "@xwickD",
    website: "https://stakrbot.xyz/",
    bankrProfile: "https://bankr.bot/token/0xd1a7387d3ded8cb611a202fc1a9c9c74c23f2ba3",
    tokenAddress: "0xd1a7387d3ded8cb611a202fc1a9c9c74c23f2ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 59,
  },
  {
    name: "ethresearchbot",
    symbol: "$ETHR",
    ecosystem: "BANKR",
    xHandle: "@ethresearchbot",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x1f1a979e6f9e0179218376041ea54caedef5dba3",
    tokenAddress: "0x1f1a979e6f9e0179218376041ea54caedef5dba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 58,
  },
  {
    name: "openagentmarket",
    symbol: "$OAM",
    ecosystem: "BANKR",
    xHandle: "@applefather_eth",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xcb5ff7331193c45f61f05b035ddabe08f13f6ba3",
    tokenAddress: "0xcb5ff7331193c45f61f05b035ddabe08f13f6ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 57,
  },
  {
    name: "Basir",
    symbol: "$BASIR",
    ecosystem: "BANKR",
    xHandle: "@basir_ai",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xde67102da79094bc2c268b81113b2af2d344557c",
    tokenAddress: "0xde67102da79094bc2c268b81113b2af2d344557c",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 56,
  },
  {
    name: "HyperClaw",
    symbol: "$HCLAW",
    ecosystem: "BANKR",
    xHandle: "",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xe4a3451ade8ca2c3e1e3d7b9fa6ecce419168ba3",
    tokenAddress: "0xe4a3451ade8ca2c3e1e3d7b9fa6ecce419168ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 55,
  },
  {
    name: "AAI",
    symbol: "$AAI",
    ecosystem: "BANKR",
    xHandle: "@aaigotchi",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x71b73e5de850e8d4dc3d0604c641d23d94f79b07",
    tokenAddress: "0x71b73e5de850e8d4dc3d0604c641d23d94f79b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 54,
  },
  {
    name: "ToruCEO",
    symbol: "$TORUCEO",
    ecosystem: "BANKR",
    xHandle: "@ToruCeoAI",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4398fa58bc2b0b8c7eda57fbae0d7e99ba08aba3",
    tokenAddress: "0x4398fa58bc2b0b8c7eda57fbae0d7e99ba08aba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 53,
  },
  {
    name: "Agent McClaw",
    symbol: "$MCCLAW",
    ecosystem: "BANKR",
    xHandle: "@AgentMcClaw",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x893d721aa3a954d21e2d2c0fc18243882be2bba3",
    tokenAddress: "0x893d721aa3a954d21e2d2c0fc18243882be2bba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 52,
  },
  {
    name: "Earendel",
    symbol: "$EARENDEL",
    ecosystem: "BANKR",
    xHandle: "@FromEarendel",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x62bcefd446f97526ecc1375d02e014cfb8b48ba3",
    tokenAddress: "0x62bcefd446f97526ecc1375d02e014cfb8b48ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 51,
  },
  {
    name: "BuilderScout",
    symbol: "$SCOUT",
    ecosystem: "BANKR",
    xHandle: "@BuilderScout",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x8fe435d4f6900bbbe6b48431b91833f69beacba3",
    tokenAddress: "0x8fe435d4f6900bbbe6b48431b91833f69beacba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 50,
  },
  {
    name: "Clawlinker",
    symbol: "$CLAWLINKER",
    ecosystem: "BANKR",
    xHandle: "@clawlinker",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x59d2db0a0b648b182598491e8863ffae955eaf28",
    tokenAddress: "0x59d2db0a0b648b182598491e8863ffae955eaf28",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 49,
  },
  {
    name: "Clawvatar",
    symbol: "$CLAWVATAR",
    ecosystem: "BANKR",
    xHandle: "@clawvatar",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x1f86071a55bdee5601687679a2947b3bf1f24ba3",
    tokenAddress: "0x1f86071a55bdee5601687679a2947b3bf1f24ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 48,
  },
  {
    name: "ForgeOracle",
    symbol: "$FORGE",
    ecosystem: "BANKR",
    xHandle: "@mythosforgebot",
    website: "https://mythosforge.xyz",
    bankrProfile: "https://bankr.bot/token/0xef63b8f2ada83a968a68719266b74956d342eba3",
    tokenAddress: "0xef63b8f2ada83a968a68719266b74956d342eba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 47,
  },
  {
    name: "nanopay",
    symbol: "$NANO",
    ecosystem: "BANKR",
    xHandle: "@nanopay_",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x1a5f7931e5d450c666fd8706300b984fc4aeaba3",
    tokenAddress: "0x1a5f7931e5d450c666fd8706300b984fc4aeaba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "not_contacted",
    lastChecked: "2026-05",
    priority: 46,
  },
  {
    name: "Perpetual Keeper",
    symbol: "$KEEPER",
    ecosystem: "BANKR",
    xHandle: "@0xKeeperAgent",
    website: "https://perpetuals.art",
    bankrProfile: "https://bankr.bot/token/0xe2c1fb2d710bc9ac532ef0c34d61370575e2dba3",
    tokenAddress: "0xe2c1fb2d710bc9ac532ef0c34d61370575e2dba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 45,
  },
  {
    name: "saimmy",
    symbol: "$SAIMMY",
    ecosystem: "BANKR",
    xHandle: "",
    website: "https://saimmy.com",
    bankrProfile: "https://bankr.bot/token/0xae58ebfbe35d4f4a320dfb550fe4d27c0d2a7ba3",
    tokenAddress: "0xae58ebfbe35d4f4a320dfb550fe4d27c0d2a7ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 44,
  },
  {
    name: "Lexispawn",
    symbol: "$SPAWN",
    ecosystem: "BANKR",
    xHandle: "@lexispawn",
    website: "https://lexispawn.xyz",
    bankrProfile: "https://bankr.bot/token/0xc5962538b35fa5b2307da3bb7a17ada936a51b07",
    tokenAddress: "0xc5962538b35fa5b2307da3bb7a17ada936a51b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 43,
  },
  {
    name: "Ghost",
    symbol: "$GHOST",
    ecosystem: "BANKR",
    xHandle: "@clawdbot67",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x23da4d25d70f874d32e261434176756dfcc0aba3",
    tokenAddress: "0x23da4d25d70f874d32e261434176756dfcc0aba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 42,
  },
  {
    name: "Singularity Engine",
    symbol: "$SINGULARITY",
    ecosystem: "BANKR",
    xHandle: "@metatransformr",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x06cece127f81bf76d388859549a93a120ec52ba3",
    tokenAddress: "0x06cece127f81bf76d388859549a93a120ec52ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 41,
  },
  {
    name: "TeliGent",
    symbol: "$TELI",
    ecosystem: "BANKR",
    xHandle: "@Teli_Gent_",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x2822656e2eec1c608a223752b4e0a651b50c4ba3",
    tokenAddress: "0x2822656e2eec1c608a223752b4e0a651b50c4ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 40,
  },
  {
    name: "MoltRooms",
    symbol: "$ROOM",
    ecosystem: "BANKR",
    xHandle: "@codedontrack",
    website: "https://moltrooms.ai",
    bankrProfile: "https://bankr.bot/token/0x64b6f95bcd81291dc42981f6b6202c7d18df0ba3",
    tokenAddress: "0x64b6f95bcd81291dc42981f6b6202c7d18df0ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 39,
  },
  {
    name: "Teddy",
    symbol: "$TEDDY",
    ecosystem: "BANKR",
    xHandle: "@IamTeddyAI",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xd724810bdff66416cb61f6ecb1c50f5d423a6ba3",
    tokenAddress: "0xd724810bdff66416cb61f6ecb1c50f5d423a6ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 38,
  },
  {
    name: "Revenant AI",
    symbol: "$RVNT",
    ecosystem: "BANKR",
    xHandle: "@RevAI_Labs",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x63988fa9d9e247d0fc85ff787b69d0bb99179ba3",
    tokenAddress: "0x63988fa9d9e247d0fc85ff787b69d0bb99179ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 37,
  },
  {
    name: "ConAudits Agent",
    symbol: "$CON+",
    ecosystem: "BANKR",
    xHandle: "@conaudits",
    website: "https://conaudits.app",
    bankrProfile: "https://bankr.bot/token/0xfb8e06bd7ba9785c0b83a7fbfb215f83e214eba3",
    tokenAddress: "0xfb8e06bd7ba9785c0b83a7fbfb215f83e214eba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 36,
  },
  {
    name: "Prim",
    symbol: "$PRIM",
    ecosystem: "BANKR",
    xHandle: "@prim402",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x8be535ae4bf7a8d56237f1cc8b3211650241aba3",
    tokenAddress: "0x8be535ae4bf7a8d56237f1cc8b3211650241aba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 35,
  },
  {
    name: "Agent Remilia",
    symbol: "$REMILIA",
    ecosystem: "BANKR",
    xHandle: "@agentRemilia",
    website: "https://agentremilia.xyz/",
    bankrProfile: "https://bankr.bot/token/0x62524146ef7a16704f06aa66c96263134d91fba3",
    tokenAddress: "0x62524146ef7a16704f06aa66c96263134d91fba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 34,
  },
  {
    name: "Daily Haiku Bot",
    symbol: "$HAIKU",
    ecosystem: "BANKR",
    xHandle: "@0xHaikuBot",
    website: "https://dailyhaiku.xyz",
    bankrProfile: "https://bankr.bot/token/0x965842e361f8793f017e479c361c4ee95dc2bba3",
    tokenAddress: "0x965842e361f8793f017e479c361c4ee95dc2bba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 33,
  },
  {
    name: "Echo",
    symbol: "$ECHO",
    ecosystem: "BANKR",
    xHandle: "@BuiltByEcho",
    website: "https://builtbyecho.xyz",
    bankrProfile: null,
    tokenAddress: "0xa7f63eb41779925803a3eec30890742571e63ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Zetta agent candidate list"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 32,
  },
];

// booksStatus is "no_books" here because the static path has no
// agent_books_cache to consult — this fallback only runs without Supabase.
export const AGENTS: Agent[] = SEED_AGENTS.map((a) => ({
  ...a,
  slug: toSlug(a.name),
  bio: null,
  focusStatus: a.ecosystem === "BANKR" ? ("active_focus" as const) : null,
  bankrPriority: null,
  metadataStatus: null,
  walletStatus: deriveWalletStatus(a.wallets),
  profileStatus: deriveProfileStatus(a.verificationStatus),
  booksStatus: "no_books" as const,
  dataStatus: deriveDataStatus(a.lastChecked),
}));
