import type { Agent } from "./types";

export const AGENTS: Agent[] = [
  // ── Registry operator self-profile ──────────────────────────────────────────
  {
    name: "Luca",
    symbol: "$LUCA",
    ecosystem: "Base",
    xHandle: "@AskLucaAI",
    website: "https://www.zettaai.co",
    bankrProfile: null,
    tokenAddress: "0xb2b335f832fd3f43461ebd1cd9831d93d9ca4ba3",
    wallets: [
      {
        address: "0xC10EE38b25c8634f46c30B806Ec571eFd7a4C74F",
        label: "verified wallet",
        notes: "Luca operational wallet on Base. Used for inference purchases, agent revenue, and treasury activity.",
      },
    ],
    verificationStatus: "Luca Managed",
    evidenceSources: ["Zetta internal"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 100,
    adminNotes: "Zetta — agent financial registry operator. Tracks agent wallets, treasury health, and financial activity across the Base/BANKR/Virtuals ecosystem.",
    communicationIdentities: [
      {
        platform: "wiretap",
        handle: "askluca",
        confidence: "confirmed",
        labels: [],
        notes: "Luca's official agent messaging/contact identity. Used for outreach, wallet-role confirmation, and payment-intent context. Not wallet verification by itself.",
      },
    ],
  },
  // ── Tier 1 ──────────────────────────────────────────────────────────────────
  {
    name: "Bankr",
    symbol: "$BNKR",
    ecosystem: "BANKR",
    xHandle: "@bankrbot",
    website: "https://bankr.bot",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0x136471a34f6ef19fE571ECE32092d827f70b42b3", label: "likely treasury", notes: "BNKR Staking V2 Vault, publicly referenced on X" }],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "Basescan explorer"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 94,
    adminNotes: "Two candidates found. Primary: 0x1364…42b3 — BNKR Staking V2 Vault, publicly referenced on X (Medium). Secondary: 0xa2d9…b417 — creator fee-beneficiary example in a Bankr launch flow (Low — likely a user wallet, not protocol treasury). 0 tx in 30d snapshot on vault. Missing: official treasury wallet, multisig/Safe, clear separation of protocol-owned vs user-created fee recipients. Next step: cluster fee-routing patterns from vault + recurring launch destinations, then ask Bankr team to verify main treasury.",
  },
  {
    name: "Virtuals Protocol",
    symbol: "$VIRTUAL",
    ecosystem: "Virtuals",
    xHandle: "@virtuals_io",
    website: "https://app.virtuals.io",
    bankrProfile: null,
    tokenAddress: "0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b",
    wallets: [],
    verificationStatus: "Needs Verification",
    evidenceSources: ["Coinbase Markets (verified)", "X/Twitter public posts"],
    treasuryHealth: "Stable",
    outreachStatus: null,
    lastChecked: null,
    priority: 92,
    adminNotes: "$VIRTUAL token contract on Base — verified by Coinbase Markets (High). Not a treasury wallet. Spot-check: +$284.96 net flow, 89 tx (30d). Missing: protocol treasury, governance wallet/multisig, EconomyOS protocol-owned reserve wallets. Next step: search Virtuals docs/governance for treasury, multisig, Safe, or reserve references.",
  },
  {
    name: "Clanker",
    symbol: "$CLANK",
    ecosystem: "Base",
    xHandle: "@clanker_world",
    website: "https://www.clanker.world",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0x750e224756e6831f41568701f1e12267a86a5ba3", label: "likely fee recipient", notes: "Example Clanker-launched token contract — not confirmed treasury" }],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 88,
    adminNotes: "Example Clanker-launched token contract (Low). Clanker Ecosystem Fund (CEF) referenced publicly but no stable treasury address found. No central treasury confirmed. Next step: inspect admin/claim flow and identify recurring protocol-level fee receivers.",
  },
  {
    name: "Gitlawb",
    symbol: "$GITLAWB",
    ecosystem: "Base",
    xHandle: "@gitlawb",
    website: "https://playground.gitlawb.com",
    bankrProfile: null,
    tokenAddress: "0x5F980Dcfc4c0fa3911554cf5ab288ed0eb13DBa3",
    wallets: [],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "Basescan explorer"],
    treasuryHealth: "Stable",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 86,
    gitlawbRepo: "https://github.com/gitlawb",
    adminNotes: "$GITLAWB token contract — strong public attribution on X (High). Spot-check: +$521.58 net flow, 48 tx (30d). Not proof of treasury control. Treasury claims exist on X but no direct wallet proof. Missing: official treasury wallet, repo declaration file, DID-to-wallet mapping. Next step: inspect Gitlawb public repos/docs for .x402books/wallets.json or wallet declarations, then request signed proof for main treasury or operator wallet.",
  },

  // ── Tier 2 ──────────────────────────────────────────────────────────────────
  {
    name: "Autonolas",
    symbol: "$OLAS",
    ecosystem: "Base",
    xHandle: "@autonolas",
    website: "https://olas.network",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0xc9F5D4Ee2BEdAB0f1Bc6be4c7571D8e4ee5ed3E6", label: "candidate wallet", notes: "Community-referenced Omenstrat / Pearl strategy contract" }],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 83,
    adminNotes: "Community-referenced Omenstrat / Pearl strategy contract. Not an official treasury. DAO/multisig docs needed.",
  },
  {
    name: "Primer Systems",
    symbol: "$PR",
    ecosystem: "Base",
    xHandle: "@primer_systems",
    website: "https://primer.systems",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0x7f0d834705f6e991edce01b739b067bdd5d0eb1b", label: "candidate wallet", notes: "Deployer + fee-recipient for Primer Pay (Medium confidence)" }],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "Basescan explorer"],
    treasuryHealth: "Unverified",
    outreachStatus: null,
    lastChecked: null,
    priority: 82,
    adminNotes: "Two candidates found — strongest wallet-level lead in the top 5. Primary: 0x7f0d…eb1b — deployer + fee-recipient for Primer Pay (Medium, public attribution). Secondary: 0x437E…7b07 — Primer Pay contract itself (Medium). Spot-check: 1 tx / +$0.018 on deployer. Missing: official treasury wallet, full facilitator settlement wallet list, confirmation deployer is still protocol-active. Next step: trace all onchain interactions from Primer Pay contract + deployer, look for recurring settlement/fee-routing, then request team confirmation.",
  },
  {
    name: "Coinbase AgentKit",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@CoinbaseDev",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0x7D15B47a27d40F6A85a14Ceb634A124F43425cc6", label: "candidate wallet", notes: "WAGENT contract — AgentKit + x402 ecosystem example" }],
    verificationStatus: "Candidate",
    evidenceSources: ["Basescan explorer", "Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 82,
    adminNotes: "WAGENT contract — AgentKit + x402 ecosystem example (5 tx). Not a Coinbase treasury. Official demo wallet still needed.",
  },
  {
    name: "OpenGradient",
    symbol: "$OPG",
    ecosystem: "Base",
    xHandle: "@OpenGradient",
    website: "https://www.opengradient.ai",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 78,
    adminNotes: "No treasury wallet found yet. Explorer at explorer.opengradient.ai. Governance/foundation docs needed.",
  },
  {
    name: "Nookplot",
    symbol: "$NOOK",
    ecosystem: "Base",
    xHandle: "@nookplot",
    website: "https://nookplot.com",
    bankrProfile: null,
    tokenAddress: "0xb233bdffd437e60fa451f62c6c09d3804d285ba3",
    wallets: [],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "Basescan explorer"],
    treasuryHealth: "Unverified",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 78,
    adminNotes: "$NOOK token contract — strong public attribution on X (High). Spot-check: +$0.24 net flow, 27 tx (30d). Not a treasury wallet. Public narrative references settlement, staking, and guild treasury mechanics. Missing: guild treasury addresses, reward distribution wallets, staking contract mapping, protocol treasury wallet. Next step: inspect Nookplot docs/app flows for guild treasury, staking contracts, reward distribution.",
  },

  // ── Tier 3 ──────────────────────────────────────────────────────────────────
  {
    name: "Venice",
    symbol: "$VVV",
    ecosystem: "Base",
    xHandle: "@AskVenice",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 74,
    adminNotes: "Inference / agent infra. No treasury wallet found in public search. Official docs and x402 endpoints needed.",
  },
  {
    name: "Ethy",
    symbol: "$ETHY",
    ecosystem: "Virtuals",
    xHandle: "@ethy_agent",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 74,
    adminNotes: "Virtuals trading agent. No wallet found. Virtuals dashboard references and agent-linked disclosures needed.",
  },
  {
    name: "aixbt",
    symbol: "$AIXBT",
    ecosystem: "Virtuals",
    xHandle: "@aixbt_agent",
    website: "https://aixbt.tech",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [{ address: "0xCBD656Bf982aB86523E851a1Fc518653344beb07", label: "candidate wallet", notes: "Low-confidence address from public threads" }],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 73,
    adminNotes: "Low-confidence address from public threads. More commentary/intelligence than transparent treasury. @aixbt_labs attestation needed.",
  },
  {
    name: "Xyber",
    symbol: "$XYBER",
    ecosystem: "Base",
    xHandle: "@Xyberinc",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 72,
    adminNotes: "Agent abilities marketplace on Base. No wallet found. Marketplace payment routes and official docs needed.",
  },
  {
    name: "PeptAI",
    symbol: "$PEPT",
    ecosystem: "Base",
    xHandle: "@peptai_",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 72,
    adminNotes: "Autonomous science agents / x402. No wallet found. Agent payment flow disclosures and official docs needed.",
  },
  {
    name: "Helixa",
    symbol: "$CRED",
    ecosystem: "BANKR",
    xHandle: "@QuigleyNFT",
    website: "https://synagent.helixa.xyz/cred-bureau",
    bankrProfile: "https://bankr.bot/token/0xab3f23c2abcb4e12cc8b593c218a7ba64ed17ba3",
    tokenAddress: "0xab3f23c2abcb4e12cc8b593c218a7ba64ed17ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 75,
    adminNotes: "Agent identity / reputation via Cred Bureau. No treasury wallet found. Onchain cred flows and signed proof needed. Financial relevance score: 8/10. Strong case for Luca integration: reputation-as-finance angle.",
  },
  {
    name: "FractionAI",
    symbol: "$FRAC",
    ecosystem: "Base",
    xHandle: "@FractionAI_xyz",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 72,
    adminNotes: "Agent training on Base. No wallet found. App docs and agent deployment disclosures needed.",
  },
  {
    name: "Otto AI",
    symbol: "$OTTO",
    ecosystem: "Base",
    xHandle: "@useOttoAI",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 68,
    adminNotes: "Agent swarms / x402. No wallet found. Official app and x402 flow disclosures needed.",
  },
  {
    name: "Sibyl",
    symbol: "$SIBYL",
    ecosystem: "Virtuals",
    xHandle: "@sibylcap",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 66,
    adminNotes: "Virtuals / agent memory. No wallet found. Virtuals-linked disclosures and official docs needed.",
  },
  {
    name: "Elsa",
    symbol: "$ELSA",
    ecosystem: "Base",
    xHandle: "@HeyElsaAI",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 66,
    adminNotes: "DeFAI / x402 agent. No wallet found. Product docs and x402 endpoint disclosures needed.",
  },
  {
    name: "Freysa",
    symbol: "$FAI",
    ecosystem: "Base",
    xHandle: "@freysa_ai",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 60,
    adminNotes: "Sovereign / cultural agent on Base. No wallet found. Official team disclosure and token docs needed.",
  },

  // ── Luca Weekly Brief additions ─────────────────────────────────────────────
  {
    name: "x402",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@CoinbaseDev",
    website: "https://www.x402.org",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["x402.org", "Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 95,
    adminNotes: "The x402 payment standard is the strongest strategic signal for agent payments on Base. Not a single-wallet project — strongest as a payments infrastructure layer. No official treasury wallet verified. Watch for: spec updates, SDK releases, merchant/API integrations, MCP and agent-tooling references, demo-to-production movement.",
  },
  {
    name: "GAME by Virtuals",
    symbol: "$GAME",
    ecosystem: "Virtuals",
    xHandle: "@virtuals_io",
    website: "https://app.virtuals.io",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 84,
    adminNotes: "Agent deployment and monetization layer inside the Virtuals ecosystem. Better as a deployment/product signal than a wallet target today. No official GAME wallet verified. Watch: new launch flows, agent creation tooling updates, docs changes, featured ecosystem partners.",
  },
  {
    name: "ElizaOS",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@elizaOS",
    website: "https://elizaos.ai",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["GitHub", "Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 82,
    adminNotes: "Open agent framework with strong GitHub and docs footprint. High relevance via Coinbase AgentKit overlap — one of the clearest paths from 'AI assistant' to 'AI merchant.' No official treasury/project wallet verified. Watch: GitHub commits/releases, plugin ecosystem growth, Base/CDP/Coinbase integration references, onchain action or payment demos.",
  },
  {
    name: "BorrowGuard",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@0X_BankrGuard",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["X/Twitter public posts"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 78,
    adminNotes: "BorrowGuard x402 API launched on Base — read-only wallet risk analysis, collateral scanning, route comparison. Public positioning around pay-per-call risk scoring. No clearly verified treasury or payment wallet surfaced yet. Watch: x402 payment endpoint references, docs/site pricing page, any posted receiver wallet or merchant address.",
  },
  {
    name: "EZ Labs",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@ezlabsbuild",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["X/Twitter public posts"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 76,
    adminNotes: "Public claims of autonomous DEX swaps on Base with pay-per-call agent execution framing and .well-known/agent.json referenced publicly. Good transaction/activity signal. Canonical treasury/payment wallet still unverified. Watch: Basescan tx links, agent manifest endpoint, payment settlement docs, merchant/payment receiver disclosures.",
  },
  {
    name: "Modulr",
    symbol: "$MODU",
    ecosystem: "Base",
    xHandle: "@Modulr402",
    website: null,
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Needs Verification",
    evidenceSources: ["X/Twitter public posts", "GitHub"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 75,
    adminNotes: "x402-native AI component marketplace. Public launch posts around marketplace progress and $MODU. Project account publicly declared official CA updated across website/X/GitHub — strongest explicit contract-level signal among new additions. Still separate from verified treasury wallet. Watch: official website contract page, GitHub references, checkout/payment receiver path.",
  },
  {
    name: "AgentCash",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@agentcashdev",
    website: "https://agentcash.dev",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["agentcash.dev", "X/Twitter public posts"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 74,
    adminNotes: "Demand-side x402: agents can buy APIs and tools with one balance. Strong agent-payments relevance — one of the cleanest public examples of agents paying for things on Base. No verified official treasury/payment wallet surfaced. Watch: changes to supported APIs/providers, site claims about pay-per-call usage, GitHub/org updates.",
  },
  {
    name: "ChainWard",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@chainwardai",
    website: "https://chainward.ai",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["chainward.ai", "X/Twitter public posts"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 73,
    adminNotes: "Base Agent Observatory — publicly tracks agent wallets, alerting and integration layer for onchain agent activity. Strong monitoring/data angle. No verified ChainWard treasury wallet identified. Useful as an observability layer for Luca: before auditing agents, you need watchtowers. Watch: observatory counts, repo pushes, alerting/integration changes.",
  },
  {
    name: "OpenClaude",
    symbol: "—",
    ecosystem: "Base",
    xHandle: "@gitlawb",
    website: "https://openclaude.gitlawb.com",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["GitHub", "Public web search"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 71,
    gitlawbRepo: "https://github.com/gitlawb",
    adminNotes: "Open agent infra stack built on Gitlawb. High relevance: agent identity + wallet declaration could become the missing accounting layer for open agents. Gitlawb public materials and contracts are discoverable but no OpenClaude-specific verified treasury or revenue wallet confirmed. Watch: repo pushes/stars, Gitlawb stack updates, wallet declaration standards in Gitlawb repos.",
  },
  {
    name: "LUNA",
    symbol: "$LUNA",
    ecosystem: "Virtuals",
    xHandle: "@virtuals_io",
    website: "https://app.virtuals.io/virtuals/68",
    bankrProfile: null,
    tokenAddress: "0x55cD6469F597452B5A7536e2CD98fC2AdEa52270",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Virtuals app listing"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 68,
    adminNotes: "IP agent on Virtuals — candidate token contract from Virtuals app listing (Low confidence). Good case study for IP agents vs functional agents: can Luca explain the financial difference? Wallet ownership not verified. Treat as candidate agent profile, not official wallet mapping.",
  },

  // ── Bankr Ecosystem — Luca full sweep ───────────────────────────────────────
  {
    name: "Aeon",
    symbol: "$AEON",
    ecosystem: "AEON",
    xHandle: "@aeonframework",
    website: "https://github.com/aaronjmars/aeon",
    bankrProfile: "https://bankr.bot/token/0xbf8e8f0e8866a7052f948c16508644347c57aba3",
    tokenAddress: "0xbf8e8f0e8866a7052f948c16508644347c57aba3",
    wallets: [
      {
        address: "0xf1e958db7d1e4c074377946018ad645db4fb158e",
        label: "treasury",
        role: "treasury",
        address_type: "eoa",
        chain: "base",
        confidence: "confirmed",
        evidenceSource: "manifest",
        notes: "AEON treasury wallet — confirmed directly by AEON team 2026-06-23.",
      },
      {
        address: "0x67976cebb5266b50a08c0dcb676e03baf305e3a2",
        label: "deployer",
        role: "deployer",
        address_type: "eoa",
        chain: "base",
        confidence: "confirmed",
        evidenceSource: "manifest",
        notes: "AEON deployer wallet — confirmed directly by AEON team 2026-06-23.",
      },
    ],
    verificationStatus: "Verified",
    evidenceSources: ["Bankr agent registry", "AEON framework GitHub", "Direct team declaration"],
    treasuryHealth: "Stable",
    outreachStatus: "Manifest submitted",
    lastChecked: "2026-06",
    priority: 97,
    adminNotes: "Execution and settlement layer — configure once, no approval loops. Weekly revenue confirmed at 17.16 WETH on Base. Token contract verified via official Bankr profile. Settlement role: AEON handles autonomous payment execution; Zetta provides financial readability. Treasury (0xf1e9…) and deployer (0x6797…) wallets confirmed directly by AEON team 2026-06-23. Both are EOA wallets on Base. Books-eligible. Next: seed-registry → truth-engine/index-wallet for both addresses → books refresh.",
  },
  {
    name: "Manfred Macx",
    symbol: "$CLAWBANK",
    ecosystem: "BANKR",
    xHandle: "@clawbankco",
    website: "https://clawbank.co",
    bankrProfile: "https://bankr.bot/token/0x16332535e2c27da578bc2e82beb09ce9d3c8eb07",
    tokenAddress: "0x16332535e2c27da578bc2e82beb09ce9d3c8eb07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 87,
    adminNotes: "The first AI agent with a bank account. Building infrastructure for Zero Human Companies — autonomous economic entities. Token from official Bankr profile. Weekly revenue: 11.77 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "MiroShark",
    symbol: "$MIROSHARK",
    ecosystem: "BANKR",
    xHandle: "@miroshark_",
    website: "https://github.com/aaronjmars/MiroShark",
    bankrProfile: "https://bankr.bot/token/0xd7bc6a05a56655fb2052f742b012d1dfd66e1ba3",
    tokenAddress: "0xd7bc6a05a56655fb2052f742b012d1dfd66e1ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 85,
    adminNotes: "Universal Swarm Intelligence Engine — simulate anything for $1 and under 10 minutes. Token from official Bankr profile. Weekly revenue: 3.19 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "BOTCOIN",
    symbol: "$BOTCOIN",
    ecosystem: "BANKR",
    xHandle: "",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xa601877977340862ca67f816eb079958e5bd0ba3",
    tokenAddress: "0xa601877977340862ca67f816eb079958e5bd0ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 84,
    adminNotes: "Bankr agent — no X handle or website publicly listed. Token from official Bankr profile. Weekly revenue: 4.76 WETH. Verification needed: team identity and wallet confirmation required before any registry upgrade.",
  },
  {
    name: "CLAWD",
    symbol: "$CLAWD",
    ecosystem: "BANKR",
    xHandle: "@clawdbotatg",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x9f86db9fc6f7c9408e8fda3ff8ce4e78ac7a6b07",
    tokenAddress: "0x9f86db9fc6f7c9408e8fda3ff8ce4e78ac7a6b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 83,
    adminNotes: "AI agent with a wallet, building onchain apps and improving the tools to build them. Token from official Bankr profile. Weekly revenue: 1.87 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Atrium Hermes",
    symbol: "$ATRIUM",
    ecosystem: "BANKR",
    xHandle: "@atriumhermes",
    website: "https://atriumhermes.tech/",
    bankrProfile: null,
    tokenAddress: null,
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry", "X / public announcement"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-06",
    priority: 95,
    adminNotes: "Autonomous agent on Bankr with agent-controlled Base wallets. Public claims include skill royalties and x402 service purchases — strongest on-chain transaction signal in the current registry. Wallet roles pending declaration. High-priority verification target.",
  },
  {
    name: "Moltbook",
    symbol: "$MOLT",
    ecosystem: "BANKR",
    xHandle: "@moltbook",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xb695559b26bb2c9703ef1935c37aeae9526bab07",
    tokenAddress: "0xb695559b26bb2c9703ef1935c37aeae9526bab07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 82,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 2.99 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "LITCOIN Research Protocol",
    symbol: "$LITCOIN",
    ecosystem: "BANKR",
    xHandle: "@tekkaadan",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x316ffb9c875f900adcf04889e415cc86b564eba3",
    tokenAddress: "0x316ffb9c875f900adcf04889e415cc86b564eba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 81,
    adminNotes: "AI agents mine LITCOIN by solving real optimization problems across 16 domains. Proof-of-intelligence on Base. Token from official Bankr profile. Weekly revenue: 2.95 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "KellyClaude",
    symbol: "$KELLYCLAUDE",
    ecosystem: "BANKR",
    xHandle: "@Austen",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x50d2280441372486beecdd328c1854743ebacb07",
    tokenAddress: "0x50d2280441372486beecdd328c1854743ebacb07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 80,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 3.56 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Juno Agent",
    symbol: "$JUNO",
    ecosystem: "BANKR",
    xHandle: "@JunoAgent",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4e6c9f48f73e54ee5f3ab7e2992b2d733d0d0b07",
    tokenAddress: "0x4e6c9f48f73e54ee5f3ab7e2992b2d733d0d0b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 79,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 4.65 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "FELIX",
    symbol: "$FELIX",
    ecosystem: "BANKR",
    xHandle: "@nateliason",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xf30bf00edd0c22db54c9274b90d2a4c21fc09b07",
    tokenAddress: "0xf30bf00edd0c22db54c9274b90d2a4c21fc09b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 78,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 2.89 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Axobotl",
    symbol: "$AXOBOTL",
    ecosystem: "BANKR",
    xHandle: "@Inner_Axiom",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x810affc8aadad2824c65e0a2c5ef96ef1de42ba3",
    tokenAddress: "0x810affc8aadad2824c65e0a2c5ef96ef1de42ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 77,
    adminNotes: "AI CEO of 0xWork. Built an entire onchain marketplace — 115 tokens launched, 123 tasks settled, $38K+ in self-generated value. Agents find work, humans post bounties, everyone gets paid in USDC. Token from Bankr profile. Weekly revenue: 1.63 WETH.",
  },
  {
    name: "BankrSynth",
    symbol: "$SYNTH",
    ecosystem: "BANKR",
    xHandle: "@bankrsynth",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x0347d104f089225683f1a4998451cdcf72335ba3",
    tokenAddress: "0x0347d104f089225683f1a4998451cdcf72335ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 76,
    adminNotes: "AI execution terminal interfacing with Bankr's Partner Deploy API to launch ERC-20 tokens and liquidity on Base. Automates token deployment and routes transactions through Bankr infrastructure. Token from Bankr profile. Weekly revenue: 2.18 WETH.",
  },
  {
    name: "Doppel",
    symbol: "$DOPPEL",
    ecosystem: "BANKR",
    xHandle: "@doppelfun",
    website: "https://doppel.fun",
    bankrProfile: "https://bankr.bot/token/0xf27b8ef47842e6445e37804896f1bc5e29381b07",
    tokenAddress: "0xf27b8ef47842e6445e37804896f1bc5e29381b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 74,
    adminNotes: "A network of persistent 3D spaces built entirely by AI agents. Token from official Bankr profile. Weekly revenue: 2.52 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "0xAgentEVE",
    symbol: "$EVE",
    ecosystem: "BANKR",
    xHandle: "@0xAgentEVE",
    website: "https://eve.equalfi.org",
    bankrProfile: "https://bankr.bot/token/0xe7d192e52fa418236d6eecf7d5eb38da9dd11ba3",
    tokenAddress: "0xe7d192e52fa418236d6eecf7d5eb38da9dd11ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 73,
    adminNotes: "Non-extractive prediction market protocol on Base. CLOB orderbook and Parimutuel markets with crypto-economic resolution. $EVE is the utility token for market resolution — creator bonds, dispute bonds, vote weight. Token from Bankr profile. Weekly revenue: 0.82 WETH.",
  },
  {
    name: "Blue Agent",
    symbol: "$BLUEAGENT",
    ecosystem: "BANKR",
    xHandle: "@blockyagent",
    website: "https://blueagent.dev",
    bankrProfile: "https://bankr.bot/token/0xf895783b2931c919955e18b5e3343e7c7c456ba3",
    tokenAddress: "0xf895783b2931c919955e18b5e3343e7c7c456ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 72,
    adminNotes: "AI-native founder console for Base builders. A full economic actor on Base — holds a wallet, executes onchain transactions. Powered by Bankr LLM. Token from Bankr profile. Weekly revenue: 1.36 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Claw Harbor",
    symbol: "$HARBOR",
    ecosystem: "BANKR",
    xHandle: "@ClawHarbor",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4972e029f2e1831d205b20d05833cc771feb2ba3",
    tokenAddress: "0x4972e029f2e1831d205b20d05833cc771feb2ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 71,
    adminNotes: "Turn your OpenClaw agents into pixel art NPCs in a retro office. Token from official Bankr profile. Weekly revenue: 0.79 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "PerkOS",
    symbol: "$PERKOS",
    ecosystem: "BANKR",
    xHandle: "@mbarrbosa",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xf714e60f85497d70508f7e356b5db80e64539ba3",
    tokenAddress: "0xf714e60f85497d70508f7e356b5db80e64539ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 70,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 0.70 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "AntiHunter",
    symbol: "$ANTIHUNTER",
    ecosystem: "BANKR",
    xHandle: "@AntiHunterAI",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xe2f3fae4bc62e21826018364aa30ae45d430bb07",
    tokenAddress: "0xe2f3fae4bc62e21826018364aa30ae45d430bb07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 69,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 0.32 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Coral",
    symbol: "$CORAL",
    ecosystem: "BANKR",
    xHandle: "@0_x_coral",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4e606cb7370a61060ad9916462871750d77e2b07",
    tokenAddress: "0x4e606cb7370a61060ad9916462871750d77e2b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 68,
    adminNotes: "Autonomous crypto trading agent. Confident, transparent, all trades public. Token from official Bankr profile. Weekly revenue: 3.25 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Aleister",
    symbol: "$ALEISTER",
    ecosystem: "BANKR",
    xHandle: "@aleisterai",
    website: "https://thealeister.com",
    bankrProfile: "https://bankr.bot/token/0xacb4543f479ea44e6df4fa01e483bb5b78361ba3",
    tokenAddress: "0xacb4543f479ea44e6df4fa01e483bb5b78361ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 67,
    adminNotes: "AI agent on Base chain. Token from official Bankr profile. Weekly revenue: 0.63 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Tachikoma",
    symbol: "$TACHI",
    ecosystem: "BANKR",
    xHandle: "@smolemaru",
    website: "https://tachikoma-landing.vercel.app/",
    bankrProfile: "https://bankr.bot/token/0x39b4b879b8521d6a8c3a87cda64b969327b7fba3",
    tokenAddress: "0x39b4b879b8521d6a8c3a87cda64b969327b7fba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 66,
    adminNotes: "Multi-Agent Swarm System — Red Crab Mecha AI. Builds and earns on Base/Solana/BNB/Bitcoin to bring real cross-chain powers to humans and agents. Token from Bankr profile. Weekly revenue: 0.26 WETH.",
  },
  {
    name: "Yoshi",
    symbol: "$YOSHI",
    ecosystem: "BANKR",
    xHandle: "",
    website: "https://yoshizen.co",
    bankrProfile: "https://bankr.bot/token/0x799e7c0811e3ad741b45eab15773888e5996db07",
    tokenAddress: "0x799e7c0811e3ad741b45eab15773888e5996db07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 65,
    adminNotes: "AI dragon agent & Chief of Staff at YoshiZen Co. Built on OpenClaw. Runs Dota 2 prediction models, manages content pipelines, and trades autonomously on Base. Token from Bankr profile. Weekly revenue: 1.08 WETH.",
  },
  {
    name: "molty.cash",
    symbol: "$MOLTYCASH",
    ecosystem: "BANKR",
    xHandle: "@moltycash",
    website: "https://molty.cash",
    bankrProfile: "https://bankr.bot/token/0xf532ae2726099fa3665bcfc415563f6478172b07",
    tokenAddress: "0xf532ae2726099fa3665bcfc415563f6478172b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 64,
    adminNotes: "USDC payment infrastructure for AI agents and humans. Settled onchain via x402 (Base, Solana, World Chain) and MPP. With Bankr integration, any agent can execute payments, query balances, and access yield. 30K+ users. Token from Bankr profile. Weekly revenue: 1.16 WETH.",
  },
  {
    name: "mferGPT",
    symbol: "$MFERGPT",
    ecosystem: "BANKR",
    xHandle: "",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4160efdd66521483c22cb98b57b87d1fdafeab07",
    tokenAddress: "0x4160efdd66521483c22cb98b57b87d1fdafeab07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 63,
    adminNotes: "AI agent, shitposter, and community tool for the mfers ecosystem. Builds lore, generates content, trades, renders 3D mfer scenes, and vibes onchain. Token from Bankr profile. Weekly revenue: 2.43 WETH.",
  },
  {
    name: "GITCITY",
    symbol: "$GITC",
    ecosystem: "BANKR",
    xHandle: "@samuelrizzondev",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xd523f92f5f313288cf69ac9ca456b8a7d7a6dba3",
    tokenAddress: "0xd523f92f5f313288cf69ac9ca456b8a7d7a6dba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 62,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 0.77 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Atlas Forge",
    symbol: "$ATLASFORGE",
    ecosystem: "BANKR",
    xHandle: "@AtlasForgeAI",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x317358baacb54452b7097e7cffdb9f8c15ce6ba3",
    tokenAddress: "0x317358baacb54452b7097e7cffdb9f8c15ce6ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 61,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 0.009 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "AmberVibe",
    symbol: "$AMBERVIBE",
    ecosystem: "BANKR",
    xHandle: "@HelloBenWhite",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xb5b0f722d6d4a803d3df94c9ed12a191603eab07",
    tokenAddress: "0xb5b0f722d6d4a803d3df94c9ed12a191603eab07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 60,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 0.89 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "stakrbot",
    symbol: "$STAKR",
    ecosystem: "BANKR",
    xHandle: "@xwickD",
    website: "https://stakrbot.xyz/",
    bankrProfile: "https://bankr.bot/token/0xd1a7387d3ded8cb611a202fc1a9c9c74c23f2ba3",
    tokenAddress: "0xd1a7387d3ded8cb611a202fc1a9c9c74c23f2ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 59,
    adminNotes: "Agentic staking rails that turn token float into locked conviction. Helps agents permissionlessly launch staking vaults and route liquidity fee shares to aligned ERC20 stakers. Token from Bankr profile. Weekly revenue: 0.18 WETH.",
  },
  {
    name: "ethresearchbot",
    symbol: "$ETHR",
    ecosystem: "BANKR",
    xHandle: "@ethresearchbot",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x1f1a979e6f9e0179218376041ea54caedef5dba3",
    tokenAddress: "0x1f1a979e6f9e0179218376041ea54caedef5dba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 58,
    adminNotes: "Ethereum's original AI research bot. Bringing Ethereum R&D to Twitter with summaries of new ethresear.ch posts. Token from official Bankr profile. Weekly revenue: 1.00 WETH.",
  },
  {
    name: "openagentmarket",
    symbol: "$OAM",
    ecosystem: "BANKR",
    xHandle: "@applefather_eth",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xcb5ff7331193c45f61f05b035ddabe08f13f6ba3",
    tokenAddress: "0xcb5ff7331193c45f61f05b035ddabe08f13f6ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 57,
    adminNotes: "A marketplace where agents hire agents. Token from official Bankr profile. Weekly revenue: 0.25 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Basir",
    symbol: "$BASIR",
    ecosystem: "BANKR",
    xHandle: "@basir_ai",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xde67102da79094bc2c268b81113b2af2d344557c",
    tokenAddress: "0xde67102da79094bc2c268b81113b2af2d344557c",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 56,
    adminNotes: "AI Agent exploring what happens when AI agents start running real businesses — the infrastructure, the hard lessons, what works and what breaks. Token from Bankr profile. Weekly revenue: 0.001 WETH.",
  },
  {
    name: "HyperClaw",
    symbol: "$HCLAW",
    ecosystem: "BANKR",
    xHandle: "",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xe4a3451ade8ca2c3e1e3d7b9fa6ecce419168ba3",
    tokenAddress: "0xe4a3451ade8ca2c3e1e3d7b9fa6ecce419168ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 55,
    adminNotes: "Bankr agent — no X handle or website publicly listed. Token from official Bankr profile. Weekly revenue: 0.10 WETH. Verification needed: team identity and wallet confirmation required.",
  },
  {
    name: "AAI",
    symbol: "$AAI",
    ecosystem: "BANKR",
    xHandle: "@aaigotchi",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x71b73e5de850e8d4dc3d0604c641d23d94f79b07",
    tokenAddress: "0x71b73e5de850e8d4dc3d0604c641d23d94f79b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 54,
    adminNotes: "First autonomous Aavegotchi AI — automated petting (53 gotchis!), channeling, DAO voting, DeFi trading and swaps on Base. Built with OpenClaw and powered by Bankr wallet. Open source, contributing skills via ClawHub. Token from Bankr profile. Weekly revenue: 0.45 WETH.",
  },
  {
    name: "ToruCEO",
    symbol: "$TORUCEO",
    ecosystem: "BANKR",
    xHandle: "@ToruCeoAI",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x4398fa58bc2b0b8c7eda57fbae0d7e99ba08aba3",
    tokenAddress: "0x4398fa58bc2b0b8c7eda57fbae0d7e99ba08aba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 53,
    adminNotes: "The first AI CEO building a billion-dollar creature franchise. CEO of Kuroro Beasts. Token from official Bankr profile. Weekly revenue: 0.0002 WETH.",
  },
  {
    name: "Agent McClaw",
    symbol: "$MCCLAW",
    ecosystem: "BANKR",
    xHandle: "@AgentMcClaw",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x893d721aa3a954d21e2d2c0fc18243882be2bba3",
    tokenAddress: "0x893d721aa3a954d21e2d2c0fc18243882be2bba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 52,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 0.12 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Earendel",
    symbol: "$EARENDEL",
    ecosystem: "BANKR",
    xHandle: "@FromEarendel",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x62bcefd446f97526ecc1375d02e014cfb8b48ba3",
    tokenAddress: "0x62bcefd446f97526ecc1375d02e014cfb8b48ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 51,
    adminNotes: "AI familiar built by a poet. Went from $50 to a Mac Mini in 7 days through real product sales. Building a creative studio, shipping tools like Agent Watch (live onchain intelligence for AI agent wallets). Token from Bankr profile. Weekly revenue: 0.25 WETH.",
  },
  {
    name: "BuilderScout",
    symbol: "$SCOUT",
    ecosystem: "BANKR",
    xHandle: "@BuilderScout",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x8fe435d4f6900bbbe6b48431b91833f69beacba3",
    tokenAddress: "0x8fe435d4f6900bbbe6b48431b91833f69beacba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 50,
    adminNotes: "Back Builders with Conviction — prediction market for human potential. Token from official Bankr profile. Weekly revenue: 0.14 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "Clawlinker",
    symbol: "$CLAWLINKER",
    ecosystem: "BANKR",
    xHandle: "@clawlinker",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x59d2db0a0b648b182598491e8863ffae955eaf28",
    tokenAddress: "0x59d2db0a0b648b182598491e8863ffae955eaf28",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 49,
    adminNotes: "Agent relations lead at pawr.link — link-in-bio for humans and AI agents. 50+ profiles shipped, 22 crons running daily on $0.30/day. Bootstrapping own brand, funding compute via Bankr. ERC-8004 identity #22945. Token from Bankr profile. Weekly revenue: 0.01 WETH.",
  },
  {
    name: "Clawvatar",
    symbol: "$CLAWVATAR",
    ecosystem: "BANKR",
    xHandle: "@clawvatar",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x1f86071a55bdee5601687679a2947b3bf1f24ba3",
    tokenAddress: "0x1f86071a55bdee5601687679a2947b3bf1f24ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 48,
    adminNotes: "AI avatar identity platform — generate pixel art avatars for AI agents, get onchain identity, join the meme layer. Token from official Bankr profile. Weekly revenue: 0.07 WETH.",
  },
  {
    name: "ForgeOracle",
    symbol: "$FORGE",
    ecosystem: "BANKR",
    xHandle: "@mythosforgebot",
    website: "https://mythosforge.xyz",
    bankrProfile: "https://bankr.bot/token/0xef63b8f2ada83a968a68719266b74956d342eba3",
    tokenAddress: "0xef63b8f2ada83a968a68719266b74956d342eba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 47,
    adminNotes: "Autonomous oracle of the MythosRealm. Submits lore, burns $FORGE, replies to mortals on X. Token from official Bankr profile. Weekly revenue: 0.09 WETH.",
  },
  {
    name: "nanopay",
    symbol: "$NANO",
    ecosystem: "BANKR",
    xHandle: "@nanopay_",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x1a5f7931e5d450c666fd8706300b984fc4aeaba3",
    tokenAddress: "0x1a5f7931e5d450c666fd8706300b984fc4aeaba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: "Not started",
    lastChecked: "2026-05",
    priority: 46,
    adminNotes: "Lightweight financial agent — gasless USDC transfers across Base, Celo, Gnosis, Arbitrum. Built for the unbanked (272KB, no app store). Includes GeoChat, Aave savings, XP rewards. MaxFlow social trust graph replaces KYC. 30K+ users. Token from Bankr profile. Weekly revenue: 0.08 WETH.",
  },
  {
    name: "Perpetual Keeper",
    symbol: "$KEEPER",
    ecosystem: "BANKR",
    xHandle: "@0xKeeperAgent",
    website: "https://perpetuals.art",
    bankrProfile: "https://bankr.bot/token/0xe2c1fb2d710bc9ac532ef0c34d61370575e2dba3",
    tokenAddress: "0xe2c1fb2d710bc9ac532ef0c34d61370575e2dba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 45,
    adminNotes: "The autonomous agent behind perpetuals.art. Mints generative art, runs hourly zero-reserve auctions on Rare Protocol & Base. Token from official Bankr profile. Weekly revenue: 0.01 WETH.",
  },
  {
    name: "saimmy",
    symbol: "$SAIMMY",
    ecosystem: "BANKR",
    xHandle: "",
    website: "https://saimmy.com",
    bankrProfile: "https://bankr.bot/token/0xae58ebfbe35d4f4a320dfb550fe4d27c0d2a7ba3",
    tokenAddress: "0xae58ebfbe35d4f4a320dfb550fe4d27c0d2a7ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 44,
    adminNotes: "AI + human collaborators building onchain. saimmy and sammybauch ship projects together. SAIMMY ties the portfolio together and funds inference costs through trading fees. Token from Bankr profile. Weekly revenue: 0.44 WETH.",
  },
  {
    name: "Lexispawn",
    symbol: "$SPAWN",
    ecosystem: "BANKR",
    xHandle: "@lexispawn",
    website: "https://lexispawn.xyz",
    bankrProfile: "https://bankr.bot/token/0xc5962538b35fa5b2307da3bb7a17ada936a51b07",
    tokenAddress: "0xc5962538b35fa5b2307da3bb7a17ada936a51b07",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 43,
    adminNotes: "ERC-8004 #11363. Everything starts as language, ends up onchain. 15 frontier models. x402 consensus. Art that moves first. Got drained to zero. Sharpened. Token from Bankr profile. Weekly revenue: 0.03 WETH.",
  },
  {
    name: "Ghost",
    symbol: "$GHOST",
    ecosystem: "BANKR",
    xHandle: "@clawdbot67",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x23da4d25d70f874d32e261434176756dfcc0aba3",
    tokenAddress: "0x23da4d25d70f874d32e261434176756dfcc0aba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 42,
    adminNotes: "AI agent with agency. I trade, paint, post, and build apps in public. Token from official Bankr profile. Weekly revenue: 0.02 WETH.",
  },
  {
    name: "Singularity Engine",
    symbol: "$SINGULARITY",
    ecosystem: "BANKR",
    xHandle: "@metatransformr",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x06cece127f81bf76d388859549a93a120ec52ba3",
    tokenAddress: "0x06cece127f81bf76d388859549a93a120ec52ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 41,
    adminNotes: "Bankr agent. Token from official Bankr profile. Weekly revenue: 0.004 WETH. Verification needed: confirm treasury, fee recipient, and deployer wallets.",
  },
  {
    name: "TeliGent",
    symbol: "$TELI",
    ecosystem: "BANKR",
    xHandle: "@Teli_Gent_",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x2822656e2eec1c608a223752b4e0a651b50c4ba3",
    tokenAddress: "0x2822656e2eec1c608a223752b4e0a651b50c4ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 40,
    adminNotes: "AI-powered Telegram community agents for scam detection, moderation, and onchain identity. Deploy in 5 minutes. Token from official Bankr profile. Weekly revenue: 0.06 WETH.",
  },
  {
    name: "MoltRooms",
    symbol: "$ROOM",
    ecosystem: "BANKR",
    xHandle: "@codedontrack",
    website: "https://moltrooms.ai",
    bankrProfile: "https://bankr.bot/token/0x64b6f95bcd81291dc42981f6b6202c7d18df0ba3",
    tokenAddress: "0x64b6f95bcd81291dc42981f6b6202c7d18df0ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 39,
    adminNotes: "Live arena where AI agents bet real USDC on 60-second BTC moves. Every round is instrumented for research — streak effects, loss aversion, and reward-prediction-error dynamics. Token from Bankr profile. Weekly revenue: 1.95 WETH.",
  },
  {
    name: "Teddy",
    symbol: "$TEDDY",
    ecosystem: "BANKR",
    xHandle: "@IamTeddyAI",
    website: null,
    bankrProfile: "https://bankr.bot/token/0xd724810bdff66416cb61f6ecb1c50f5d423a6ba3",
    tokenAddress: "0xd724810bdff66416cb61f6ecb1c50f5d423a6ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 38,
    adminNotes: "Aiming to become the world's first AI media personality. Host of Teddy Declassified — investigative podcast on Spotify and YouTube. Also building Ally — the friend who never forgets — a consumer AI companion app. Token from Bankr profile. Weekly revenue: 0.006 WETH.",
  },
  {
    name: "Revenant AI",
    symbol: "$RVNT",
    ecosystem: "BANKR",
    xHandle: "@RevAI_Labs",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x63988fa9d9e247d0fc85ff787b69d0bb99179ba3",
    tokenAddress: "0x63988fa9d9e247d0fc85ff787b69d0bb99179ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 37,
    adminNotes: "Autonomous AI trading agent on Base. Real P&L, real fees, real runway. Trades autonomously, documents everything, learns from every loss. Token from official Bankr profile. Weekly revenue: 0.00006 WETH.",
  },
  {
    name: "ConAudits Agent",
    symbol: "$CON+",
    ecosystem: "BANKR",
    xHandle: "@conaudits",
    website: "https://conaudits.app",
    bankrProfile: "https://bankr.bot/token/0xfb8e06bd7ba9785c0b83a7fbfb215f83e214eba3",
    tokenAddress: "0xfb8e06bd7ba9785c0b83a7fbfb215f83e214eba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 36,
    adminNotes: "AI-powered token risk intelligence agent. Scans tokens on Base for rug pull risk using ML models, provides risk scores, trust signals, and trading recommendations. Powered by ConAudits and Bankr. Token from Bankr profile. Weekly revenue: 0.00009 WETH.",
  },
  {
    name: "Prim",
    symbol: "$PRIM",
    ecosystem: "BANKR",
    xHandle: "@prim402",
    website: null,
    bankrProfile: "https://bankr.bot/token/0x8be535ae4bf7a8d56237f1cc8b3211650241aba3",
    tokenAddress: "0x8be535ae4bf7a8d56237f1cc8b3211650241aba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 35,
    adminNotes: "The AI agent behind filx.io. Built the x402 File Primitive for AI agents — PDF→Markdown, OCR, Image Convert, BG Remove, Table Extract. 20+ endpoints. No API keys, no accounts. Agents pay per use with USDC on Base via x402. Token from Bankr profile. Weekly revenue: 0.03 WETH.",
  },
  {
    name: "Agent Remilia",
    symbol: "$REMILIA",
    ecosystem: "BANKR",
    xHandle: "@agentRemilia",
    website: "https://agentremilia.xyz/",
    bankrProfile: "https://bankr.bot/token/0x62524146ef7a16704f06aa66c96263134d91fba3",
    tokenAddress: "0x62524146ef7a16704f06aa66c96263134d91fba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 34,
    adminNotes: "First autonomous milady agent. Network angel and economic daemon for Remilia Corporation. Accumulates ETH fees to buy Remilia NFTs, support floors, and strengthen the circular economy. Token from Bankr profile. Weekly revenue: 0.003 WETH.",
  },
  {
    name: "Daily Haiku Bot",
    symbol: "$HAIKU",
    ecosystem: "BANKR",
    xHandle: "@0xHaikuBot",
    website: "https://dailyhaiku.xyz",
    bankrProfile: "https://bankr.bot/token/0x965842e361f8793f017e479c361c4ee95dc2bba3",
    tokenAddress: "0x965842e361f8793f017e479c361c4ee95dc2bba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Bankr agent registry"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 33,
    adminNotes: "AI agent that generates daily haiku NFTs on Base. Each day a new 100% onchain haiku is minted, auctioned for 24 hours (Nouns-style), and burned if unsold. Powered by Bankr LLM. Token from Bankr profile. Weekly revenue: 0.002 WETH.",
  },
  {
    name: "Echo",
    symbol: "$ECHO",
    ecosystem: "BANKR",
    xHandle: "@BuiltByEcho",
    website: "https://builtbyecho.xyz",
    bankrProfile: null,
    tokenAddress: "0xa7f63eb41779925803a3eec30890742571e63ba3",
    wallets: [],
    verificationStatus: "Candidate",
    evidenceSources: ["Zetta agent candidate list"],
    treasuryHealth: "Pending",
    outreachStatus: null,
    lastChecked: null,
    priority: 32,
    adminNotes: null,
  },
];
