"use client";

import Link from "next/link";
import { LedgerCard, LedgerRow } from "@/components/ui/ledger";

export default function ReportsPage() {
  return (
    <div className="op-page">
      <div className="op-page-header-row">
        <div>
          <h1 className="op-page-title">Reports</h1>
          <p className="op-page-sub">Luca-generated financial reports for your agents.</p>
        </div>
        <Link href="/research" className="op-btn" target="_blank">View Published Research ↗</Link>
      </div>

      {/* Quick generate — each card opens Luca with the report prompt prefilled */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 12, marginBottom: 20 }}>
        {[
          { title: "Books Report · 30d", desc: "Revenue, expenses, net income and confidence for the last 30 days.", q: "Generate my 30d books report." },
          { title: "Treasury Snapshot", desc: "Current stablecoin balances across declared wallets, with runway.", q: "What's my treasury health and runway?" },
          { title: "Revenue Quality Audit", desc: "Settlement vs token revenue, quarantined inflows, and unknowns.", q: "Audit my revenue quality: what's settlement revenue vs quarantined or unknown?" },
        ].map((c) => (
          <div key={c.title} style={{ padding: "16px 18px", border: "1px solid var(--line)", borderRadius: "var(--radius-card)", background: "var(--surface)", display: "flex", flexDirection: "column", gap: 8 }}>
            <p style={{ margin: 0, fontSize: "0.86rem", fontWeight: 700, color: "var(--ink)" }}>{c.title}</p>
            <p style={{ margin: 0, fontSize: "0.74rem", color: "var(--muted)", lineHeight: 1.55, flex: 1 }}>{c.desc}</p>
            <Link href={`/dashboard/luca?q=${encodeURIComponent(c.q)}`} className="op-btn" style={{ fontSize: "0.75rem", alignSelf: "flex-start" }}>
              Generate with Luca →
            </Link>
          </div>
        ))}
      </div>

      {/* Generate reports */}
      <LedgerCard eyebrow="On-demand" title="Agent Financial Reports">
        <LedgerRow
          first
          label="Report types"
          value="Weekly · Monthly · Quarterly"
          valueStyle={{ color: "var(--muted)", fontFamily: "inherit", fontWeight: 400 }}
        />
        <LedgerRow
          label="Generated by"
          value="Luca"
          valueStyle={{ color: "var(--accent)" }}
        />
        <LedgerRow
          label="Includes"
          value="Revenue attribution, treasury health, settlement patterns, operational verdicts"
          valueStyle={{ color: "var(--muted)", fontFamily: "inherit", fontWeight: 400, fontSize: "0.75rem" }}
        />
        <LedgerRow
          last
          label="API endpoint"
          value={
            <code style={{ fontFamily: "var(--font-mono)", fontSize: "0.74rem", background: "var(--surface-soft)", padding: "4px 8px", borderRadius: 4, color: "var(--ink)" }}>
              POST /api/v1/luca/analyze
            </code>
          }
        />
      </LedgerCard>

      <div style={{ padding: "10px 14px", background: "var(--surface-soft)", borderRadius: 8, border: "1px solid var(--line)", fontSize: "0.78rem", color: "var(--muted)", marginBottom: 24 }}>
        On-demand agent report generation is available to verified operators. Contact the Zetta team to enable for your workspace, or call{" "}
        <code style={{ fontFamily: "var(--font-mono)", fontSize: "0.72rem" }}>POST /api/v1/luca/analyze {`{ "agent_id": "your-agent" }`}</code>
      </div>

      {/* Published economy reports */}
      <LedgerCard
        eyebrow="Research"
        title="Published Economy Reports"
        action={
          <Link href="/research" className="op-btn op-btn-ghost" style={{ fontSize: "0.75rem" }} target="_blank">All reports ↗</Link>
        }
      >
        <div className="op-empty" style={{ margin: 0, padding: "24px 14px" }}>
          <p className="op-empty-title">Economy-wide reports</p>
          <p className="op-empty-desc">
            Zetta publishes periodic State of the Agent Economy reports. Your agent&apos;s data contributes to the ecosystem aggregate once fully attributed.
          </p>
          <Link href="/research" className="op-btn" target="_blank">View Research →</Link>
        </div>
      </LedgerCard>
    </div>
  );
}
