"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { Logo } from "@/components/logo";
import { FadeContent, ThemeToggle } from "@/components/effects";
import Link from "next/link";

// ── Data ──────────────────────────────────────────────────────────────────────

const PROBLEMS = [
  {
    title: "Wallet roles are unclear",
    body: "Agents launch with multiple wallets. Nobody declares which holds treasury, which collects fees, which deploys contracts.",
  },
  {
    title: "Treasury is invisible",
    body: "Is the agent funded? Is it solvent? You can't tell without scanning addresses manually and guessing at intent.",
  },
  {
    title: "Trust takes too long",
    body: "Operators and builders verify everything manually. There is no standard financial identity for autonomous agents.",
  },
];

const HOW_IT_WORKS = [
  { num: "01", title: "Declare wallets",       body: "Submit a wallet manifest — treasury, fee, deployer, operator — via file or API." },
  { num: "02", title: "x402Books indexes",     body: "Wallet roles recorded. On-chain activity scanned. Treasury health derived." },
  { num: "03", title: "Luca interprets",       body: "Settlement patterns classified. Operational signals surfaced. Cold verdict generated." },
  { num: "04", title: "Profile goes live",     body: "Public profile. Embeddable card. Shareable and verifiable — travels anywhere." },
];

const ECOSYSTEMS = [
  { name: "BANKR",      color: "#6DB874" },
  { name: "Virtuals",   color: "#5B8FA8" },
  { name: "AEON",       color: "#8B5CF6" },
  { name: "EigenCloud", color: "#F97316" },
  { name: "Base",       color: "#4F46E5" },
];

const LUCA_PERKS = [
  {
    title: "Deep financial analysis",
    body: "Luca goes beyond surface-level scores. Full settlement classification, treasury runway, counterparty concentration — the complete picture.",
  },
  {
    title: "Premium treasury reports",
    body: "Audit-ready financial reports for your agent. Shareable, compliance-friendly, generated by Luca on demand.",
  },
  {
    title: "Priority verification",
    body: "Skip the queue. $LUCA holders get priority wallet manifest review and faster profile upgrades.",
  },
];

const FAQ_ITEMS = [
  {
    q: "What is x402Books?",
    a: "x402Books is the financial identity and intelligence layer for autonomous agents. Agents declare wallets, x402Books indexes activity, and Luca generates readable financial profiles — public, verifiable, shareable.",
  },
  {
    q: "What is the Agent Financial Registry?",
    a: "The Registry is the public financial identity layer for the agent economy. 84+ agents tracked with wallet roles, treasury health, settlement patterns, and Luca verification.",
  },
  {
    q: "How does verification work?",
    a: "Agents submit a wallet manifest declaring treasury, fee, deployer, and operator wallets. x402Books reviews and upgrades the profile: Candidate → Wallets Declared → Verified → Live Financial Data.",
  },
  {
    q: "What is $LUCA?",
    a: "$LUCA is the ecosystem token for Luca. Hold it to unlock deep financial analysis, premium treasury reports, and priority verification for your agent profile.",
  },
];

const LUCA_CA = "0xb2b335f832fd3f43461ebd1cd9831d93d9ca4ba3";

const SOCIAL = [
  {
    href: "https://x.com/x402Books",
    label: "X (Twitter)",
    icon: (
      <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
        <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.744l7.737-8.835L1.255 2.25H8.08l4.259 5.63L18.244 2.25zm-1.161 17.52h1.833L7.084 4.126H5.117L17.083 19.77z" />
      </svg>
    ),
  },
  {
    href: "https://t.me/x402books",
    label: "Telegram",
    icon: (
      <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
        <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z" />
      </svg>
    ),
  },
];

// ── Token helpers ─────────────────────────────────────────────────────────────

type TokenData = { price: number; change24h: number; mcap: number; volume24h: number; dexUrl: string };
type SparkPoint = { ts: number; price: number };

function formatUsd(n: number) {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(1)}K`;
  return `$${n.toFixed(2)}`;
}
function formatPrice(n: number) {
  if (n >= 1) return `$${n.toFixed(4)}`;
  if (n >= 0.001) return `$${n.toFixed(5)}`;
  if (n >= 0.000001) return `$${n.toFixed(8)}`;
  return `$${n.toFixed(10)}`;
}

function Sparkline({ points }: { points: SparkPoint[] }) {
  if (points.length < 2) return null;
  const prices = points.map((p) => p.price);
  const min = Math.min(...prices), max = Math.max(...prices);
  const range = max - min || 1;
  const W = 400, H = 56, PAD = 2;
  const coords = points.map((p, i) => {
    const x = PAD + (i / (points.length - 1)) * (W - PAD * 2);
    const y = H - PAD - ((p.price - min) / range) * (H - PAD * 2);
    return `${x},${y}`;
  });
  const isUp = prices[prices.length - 1] >= prices[0];
  const color = isUp ? "#6DB874" : "#e05252";
  const fill = `${coords[0]} L ${coords.join(" L ")} L ${W - PAD},${H} L ${PAD},${H} Z`;
  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="lp-token-sparkline" preserveAspectRatio="none">
      <defs>
        <linearGradient id="spark-fill" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor={color} stopOpacity="0.18" />
          <stop offset="100%" stopColor={color} stopOpacity="0" />
        </linearGradient>
      </defs>
      <path d={`M ${fill}`} fill="url(#spark-fill)" />
      <polyline points={coords.join(" ")} fill="none" stroke={color} strokeWidth="1.5" strokeLinejoin="round" strokeLinecap="round" />
    </svg>
  );
}

// ── $LUCA token section ───────────────────────────────────────────────────────

function LucaTokenSection() {
  const [token, setToken]         = useState<TokenData | null>(null);
  const [spark, setSpark]         = useState<SparkPoint[]>([]);
  const [copied, setCopied]       = useState(false);
  const [flashClass, setFlashClass] = useState("");
  const prevPrice = useRef<number | null>(null);

  const fetchToken = useCallback(async () => {
    try {
      const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${LUCA_CA}`, { signal: AbortSignal.timeout(6_000) });
      if (!res.ok) return;
      type DexPair = { priceUsd?: string; priceChange?: { h24?: number }; volume?: { h24?: number }; fdv?: number; marketCap?: number; url?: string };
      const data = await res.json() as { pairs?: DexPair[] };
      const pair = data.pairs?.[0];
      if (!pair) return;
      const price = parseFloat(pair.priceUsd ?? "0");
      if (price > 0 && prevPrice.current !== null && price !== prevPrice.current) {
        const cls = price > prevPrice.current ? "flash-up" : "flash-down";
        setFlashClass(cls);
        setTimeout(() => setFlashClass(""), 800);
      }
      prevPrice.current = price;
      setToken({ price, change24h: pair.priceChange?.h24 ?? 0, mcap: pair.marketCap ?? pair.fdv ?? 0, volume24h: pair.volume?.h24 ?? 0, dexUrl: pair.url ?? `https://dexscreener.com/base/${LUCA_CA}` });
    } catch { /* silent */ }
  }, []);

  useEffect(() => { fetchToken(); const iv = setInterval(fetchToken, 30_000); return () => clearInterval(iv); }, [fetchToken]);
  useEffect(() => {
    fetch(`/api/token/chart?address=${LUCA_CA}`).then(r => r.json()).then((d: { prices?: SparkPoint[] }) => { if (d.prices?.length) setSpark(d.prices); }).catch(() => {});
  }, []);

  function copy() { navigator.clipboard.writeText(LUCA_CA).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); }); }
  const changeDir = !token ? "flat" : token.change24h > 0 ? "up" : token.change24h < 0 ? "down" : "flat";

  return (
    <section className="lp-token-section">
      <div className="lp-token-card">
        <div className="lp-token-left">
          <p className="lp-token-eyebrow">Ecosystem Token · Base</p>
          <h2 className="lp-token-name">$LUCA</h2>
          <p className="lp-token-desc">
            Hold $LUCA to unlock the full power of Luca — deep financial analysis, premium treasury reports, and priority verification for your agent profile.
          </p>
          <div className="lp-luca-perks-list">
            {LUCA_PERKS.map((p) => (
              <div key={p.title} className="lp-luca-perk-row">
                <span className="lp-luca-perk-dot" />
                <div>
                  <p className="lp-luca-perk-title">{p.title}</p>
                  <p className="lp-luca-perk-body">{p.body}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="lp-token-ca">
            <span className="lp-token-ca-label">CA</span>
            <span className="lp-token-ca-addr">{LUCA_CA}</span>
            <button type="button" className="lp-token-ca-copy" onClick={copy} title="Copy">
              <span className="material-symbols-outlined" style={{ fontSize: 15 }}>{copied ? "check" : "content_copy"}</span>
            </button>
          </div>
          <div className="lp-token-links">
            <a href={token?.dexUrl ?? `https://dexscreener.com/base/${LUCA_CA}`} target="_blank" rel="noreferrer" className="lp-token-link lp-token-link-primary">Buy $LUCA</a>
            <a href={token?.dexUrl ?? `https://dexscreener.com/base/${LUCA_CA}`} target="_blank" rel="noreferrer" className="lp-token-link lp-token-link-ghost">DexScreener ↗</a>
          </div>
        </div>
        <div className="lp-token-right">
          {!token ? (
            <div className="lp-token-loading"><span className="lp-token-live-dot" />Fetching live data…</div>
          ) : (
            <>
              <div>
                <div className="lp-token-price-row">
                  <span className={`lp-token-price ${flashClass}`}>{formatPrice(token.price)}</span>
                  <span className={`lp-token-change ${changeDir}`}>{changeDir === "up" ? "▲" : changeDir === "down" ? "▼" : ""}{Math.abs(token.change24h).toFixed(2)}%</span>
                </div>
                {spark.length > 1 && (<><Sparkline points={spark} /><p className="lp-token-spark-label">7-day price chart</p></>)}
                <div className="lp-token-stats">
                  <div className="lp-token-stat"><div className="lp-token-stat-label">Market Cap</div><div className="lp-token-stat-value">{token.mcap > 0 ? formatUsd(token.mcap) : "—"}</div></div>
                  <div className="lp-token-stat"><div className="lp-token-stat-label">24h Volume</div><div className="lp-token-stat-value">{token.volume24h > 0 ? formatUsd(token.volume24h) : "—"}</div></div>
                </div>
              </div>
              <div className="lp-token-live"><span className="lp-token-live-dot" />Live · updates every 30s</div>
            </>
          )}
        </div>
      </div>
    </section>
  );
}

// ── FAQ item ──────────────────────────────────────────────────────────────────

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`lp-faq-item${open ? " open" : ""}`}>
      <button type="button" className="lp-faq-q" onClick={() => setOpen((v) => !v)}>
        <span>{q}</span>
        <span className="lp-faq-icon" aria-hidden="true">{open ? "−" : "+"}</span>
      </button>
      {open && <p className="lp-faq-a">{a}</p>}
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function HomePage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  useEffect(() => {
    document.body.style.overflow = mobileMenuOpen ? "hidden" : "";
    return () => { document.body.style.overflow = ""; };
  }, [mobileMenuOpen]);

  return (
    <div className="lp-root">

      {/* ── Header ── */}
      <header className="lp-header">
        <a href="/" className="lp-brand"><Logo /></a>
        <nav className="lp-nav" aria-label="Main navigation">
          <Link href="/registry">Registry</Link>
          <Link href="/luca">Luca</Link>
          <Link href="/developer">API</Link>
          <Link href="/docs">Docs</Link>
        </nav>
        <div className="lp-header-right">
          <div className="lp-social-icons lp-social-icons-desktop">
            {SOCIAL.map((s) => (
              <a key={s.href} href={s.href} target="_blank" rel="noreferrer" aria-label={s.label} className="lp-social-icon">{s.icon}</a>
            ))}
          </div>
          <ThemeToggle />
          <Link href="/access" className="lp-btn-ghost lp-signin-desktop">Sign In</Link>
          <Link href="/registry" className="lp-btn-primary">Explore Registry</Link>
          <button type="button" className="lp-hamburger" aria-label="Open menu" onClick={() => setMobileMenuOpen(true)}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
              <line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/>
            </svg>
          </button>
        </div>
      </header>

      {/* ── Mobile menu ── */}
      {mobileMenuOpen && (
        <div className="lp-mobile-menu" role="dialog" aria-modal="true">
          <div className="lp-mobile-menu-head">
            <a href="/" className="lp-brand" onClick={() => setMobileMenuOpen(false)}><Logo /></a>
            <button type="button" className="lp-mobile-close" onClick={() => setMobileMenuOpen(false)} aria-label="Close menu">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
              </svg>
            </button>
          </div>
          <nav className="lp-mobile-nav">
            <Link href="/registry" onClick={() => setMobileMenuOpen(false)}>Registry</Link>
            <Link href="/luca" onClick={() => setMobileMenuOpen(false)}>Luca</Link>
            <Link href="/developer" onClick={() => setMobileMenuOpen(false)}>API</Link>
            <Link href="/docs" onClick={() => setMobileMenuOpen(false)}>Docs</Link>
          </nav>
          <div className="lp-mobile-menu-footer">
            <div className="lp-social-icons">
              {SOCIAL.map((s) => (
                <a key={s.href} href={s.href} target="_blank" rel="noreferrer" aria-label={s.label} className="lp-social-icon">{s.icon}</a>
              ))}
            </div>
            <div className="lp-mobile-ctas">
              <Link href="/access" className="lp-btn-ghost" onClick={() => setMobileMenuOpen(false)}>Sign In</Link>
              <Link href="/registry" className="lp-btn-primary" onClick={() => setMobileMenuOpen(false)}>Explore Registry</Link>
            </div>
          </div>
        </div>
      )}

      {/* ── Hero ── */}
      <section className="lp-hero">
        <div className="lp-hero-copy">
          <FadeContent>
            <p className="lp-eyebrow">Financial Infrastructure · Autonomous Entities</p>
            <h1 className="lp-h1">
              Financial identity for<br />
              <em>autonomous agents.</em>
            </h1>
            <p className="lp-hero-sub">
              x402Books gives agents verified financial profiles, wallet-role clarity, and treasury intelligence — powered by Luca.
            </p>
            <div className="lp-hero-actions">
              <Link href="/registry" className="lp-btn-primary lp-btn-lg">Explore Registry</Link>
              <Link href="/luca" className="lp-btn-ghost lp-btn-lg">View Luca</Link>
            </div>
          </FadeContent>
        </div>

        {/* Agent profile card */}
        <div className="lp-hero-card" aria-label="Agent financial profile preview">
          <div className="lp-card-header">
            <span className="lp-card-dot green" /><span className="lp-card-dot yellow" /><span className="lp-card-dot red" />
            <span className="lp-card-title">Agent Financial Profile</span>
          </div>
          <div style={{ padding: "16px 18px" }}>
            <div style={{ display: "flex", alignItems: "baseline", gap: 8, marginBottom: 12 }}>
              <span style={{ fontWeight: 700, fontSize: "1.05rem" }}>Luca</span>
              <span style={{ fontSize: "0.72rem", color: "var(--muted)" }}>$LUCA</span>
            </div>
            <div style={{ display: "flex", gap: 6, marginBottom: 16 }}>
              {[{ l: "BANKR", c: "#6DB874" }, { l: "Healthy", c: "#6DB874" }, { l: "Verified", c: "#6DB874" }].map((b) => (
                <span key={b.l} style={{ fontSize: "0.67rem", fontWeight: 600, padding: "2px 8px", borderRadius: 99, border: `1px solid color-mix(in srgb, ${b.c} 28%, transparent)`, background: `color-mix(in srgb, ${b.c} 10%, transparent)`, color: b.c }}>
                  {b.l}
                </span>
              ))}
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", borderTop: "1px solid var(--line)", borderBottom: "1px solid var(--line)", marginBottom: 14 }}>
              <div>
                <p style={{ margin: 0, fontSize: "0.58rem", color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 3 }}>Profile Status</p>
                <p style={{ margin: 0, fontSize: "0.78rem", fontWeight: 700, color: "#6DB874" }}>Live Financial Data</p>
              </div>
              <div style={{ textAlign: "right" }}>
                <p style={{ margin: 0, fontSize: "0.58rem", color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 3 }}>Data Confidence</p>
                <p style={{ margin: 0, fontSize: "0.78rem", fontWeight: 700, color: "#6DB874" }}>High</p>
              </div>
            </div>
            {[["Financial Activity", 90, "#6DB874"], ["Partnership Fit", 64, "#5B8FA8"]].map(([l, pct, c]) => (
              <div key={String(l)} style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
                <span style={{ fontSize: "0.72rem", color: "var(--muted)", width: 120, flexShrink: 0 }}>{l}</span>
                <div style={{ flex: 1, height: 4, background: "var(--line)", borderRadius: 99, overflow: "hidden" }}>
                  <div style={{ width: `${pct}%`, height: "100%", background: c as string, borderRadius: 99 }} />
                </div>
                <span style={{ fontSize: "0.72rem", fontWeight: 700, width: 22, textAlign: "right" }}>{pct}</span>
              </div>
            ))}
            <div style={{ display: "flex", gap: 6, marginTop: 14 }}>
              {[{ l: "Stable Treasury", c: "#6DB874" }, { l: "Recurring Flows", c: "#5B8FA8" }].map((p) => (
                <span key={p.l} style={{ fontSize: "0.66rem", fontWeight: 600, padding: "3px 9px", borderRadius: 99, border: `1px solid color-mix(in srgb, ${p.c} 28%, transparent)`, background: `color-mix(in srgb, ${p.c} 9%, transparent)`, color: p.c }}>
                  {p.l}
                </span>
              ))}
            </div>
          </div>
          <div style={{ padding: "10px 18px", borderTop: "1px solid var(--line)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <span style={{ fontSize: "0.68rem", color: "var(--muted)", fontWeight: 600 }}>x402Books AI</span>
            <Link href="/registry/luca" style={{ fontSize: "0.68rem", fontWeight: 600, color: "var(--accent)" }}>Full profile →</Link>
          </div>
        </div>
      </section>

      {/* ── Problem ── */}
      <section className="lp-section lp-section-alt">
        <FadeContent delay={60}>
          <div className="lp-section-head">
            <p className="lp-section-label">The problem</p>
            <h2 className="lp-h2">Agents are moving money.<br />Nobody knows who to trust.</h2>
          </div>
          <div className="lp-problem-grid">
            {PROBLEMS.map((p) => (
              <div key={p.title} className="lp-problem-card">
                <h3>{p.title}</h3>
                <p>{p.body}</p>
              </div>
            ))}
          </div>
        </FadeContent>
      </section>

      {/* ── Registry ── */}
      <section className="lp-section" id="registry">
        <FadeContent delay={60}>
          <div className="lp-registry-inner">
            <div className="lp-registry-text">
              <p className="lp-section-label">Agent Financial Registry</p>
              <h2 className="lp-h2" style={{ margin: "10px 0 12px" }}>Public financial profiles<br />for every agent.</h2>
              <p className="lp-registry-sub">Wallet roles declared. Treasury visible. Settlement classified. Luca&apos;s verdict attached. Embeddable anywhere.</p>
              <div className="lp-registry-stats">
                <div className="lp-registry-stat"><strong>84+</strong><span>Agents</span></div>
                <div className="lp-registry-stat"><strong>5</strong><span>Ecosystems</span></div>
                <div className="lp-registry-stat"><strong>Live</strong><span>Profiles</span></div>
              </div>
              <div style={{ display: "flex", gap: 10, marginTop: "1.4rem", flexWrap: "wrap" }}>
                <Link href="/registry" className="lp-btn-primary">Explore Registry →</Link>
                <Link href="/registry#verify" className="lp-btn-ghost">Claim your profile</Link>
              </div>
            </div>

            <div className="lp-registry-card">
              <div className="lp-card-header">
                <span className="lp-card-dot green" /><span className="lp-card-dot yellow" /><span className="lp-card-dot red" />
                <span className="lp-card-title">Registry</span>
              </div>
              <div style={{ padding: "6px 14px 12px" }}>
                {[
                  { name: "Luca",       eco: "BANKR",    health: "Healthy", score: 90, ecoC: "#6DB874" },
                  { name: "AEON",       eco: "AEON",     health: "Stable",  score: 72, ecoC: "#8B5CF6" },
                  { name: "nanopay",    eco: "Virtuals", health: "Healthy", score: 88, ecoC: "#5B8FA8" },
                  { name: "Helixa",     eco: "BANKR",    health: "Healthy", score: 80, ecoC: "#6DB874" },
                  { name: "BankrSynth", eco: "BANKR",    health: "Watch",   score: 65, ecoC: "#6DB874" },
                ].map((a) => (
                  <div key={a.name} style={{ display: "flex", alignItems: "center", gap: 8, padding: "9px 0", borderBottom: "1px solid var(--line)" }}>
                    <span style={{ fontWeight: 600, fontSize: "0.82rem", flex: 1 }}>{a.name}</span>
                    <span style={{ fontSize: "0.65rem", fontWeight: 600, padding: "2px 7px", borderRadius: 99, border: `1px solid color-mix(in srgb, ${a.ecoC} 28%, transparent)`, background: `color-mix(in srgb, ${a.ecoC} 9%, transparent)`, color: a.ecoC }}>{a.eco}</span>
                    <span style={{ fontSize: "0.72rem", color: a.health === "Watch" ? "#f59e0b" : "var(--accent)", width: 46, textAlign: "right" }}>{a.health}</span>
                    <span style={{ fontSize: "0.78rem", fontWeight: 700, color: "var(--accent)", width: 22, textAlign: "right" }}>{a.score}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </FadeContent>
      </section>

      {/* ── Luca ── */}
      <section className="lp-section lp-section-alt" id="luca">
        <FadeContent delay={60}>
          <div className="lp-registry-inner">
            <div className="lp-registry-card" style={{ order: 0 }}>
              <div className="lp-card-header">
                <span className="lp-card-dot green" /><span className="lp-card-dot yellow" /><span className="lp-card-dot red" />
                <span className="lp-card-title">Luca · Financial Intelligence</span>
              </div>
              <div style={{ padding: "10px 14px 14px", display: "flex", flexDirection: "column", gap: 10 }}>
                {[
                  { agent: "AEON", verdict: "Stable treasury. Heavy outbound settlement. Recurring flow detected across 3 wallets.", pattern: "Stable Treasury", c: "#6DB874" },
                  { agent: "Virtuals #2", verdict: "Revenue generating. Inflow exceeds outflow 2.1×. Wallet roles unverified.", pattern: "Revenue", c: "#5B8FA8" },
                  { agent: "BankrSynth", verdict: "Dormant. No settlement activity in 14 days. Declare wallets to unlock analysis.", pattern: "Dormant", c: "#7d828d" },
                ].map((item) => (
                  <div key={item.agent} style={{ padding: "10px 12px", background: "var(--surface-soft)", border: "1px solid var(--line)", borderRadius: 8 }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 5 }}>
                      <span style={{ fontWeight: 700, fontSize: "0.82rem" }}>{item.agent}</span>
                      <span style={{ fontSize: "0.64rem", fontWeight: 600, padding: "2px 8px", borderRadius: 99, border: `1px solid color-mix(in srgb, ${item.c} 28%, transparent)`, background: `color-mix(in srgb, ${item.c} 9%, transparent)`, color: item.c }}>{item.pattern}</span>
                    </div>
                    <p style={{ margin: 0, fontSize: "0.74rem", color: "var(--muted)", lineHeight: 1.5 }}>{item.verdict}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="lp-registry-text" style={{ order: 1 }}>
              <p className="lp-section-label">Luca</p>
              <h2 className="lp-h2" style={{ margin: "10px 0 12px" }}>Turns raw activity<br />into intelligence.</h2>
              <p className="lp-registry-sub">Not a chatbot. A financial intelligence agent that classifies settlement patterns, interprets treasury behavior, and generates cold operational verdicts.</p>
              <div style={{ display: "flex", flexDirection: "column", gap: 7, margin: "16px 0" }}>
                {["Treasury health · Stable, Watch, At Risk", "Settlement patterns · 10 classification types", "Wallet role analysis · treasury, fee, deployer, operator", "Recurring flows, dormancy, counterparty concentration"].map((item) => (
                  <div key={item} style={{ display: "flex", gap: 8, fontSize: "0.82rem", color: "var(--muted)", alignItems: "flex-start" }}>
                    <span style={{ color: "var(--accent)", flexShrink: 0, marginTop: 1 }}>→</span>{item}
                  </div>
                ))}
              </div>
              <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
                <Link href="/luca" className="lp-btn-primary">View Luca →</Link>
                <a href="https://t.me/AskLucaBot" target="_blank" rel="noreferrer" className="lp-btn-ghost">Talk to Luca</a>
              </div>
            </div>
          </div>
        </FadeContent>
      </section>

      {/* ── How it works ── */}
      <section className="lp-section" id="how">
        <FadeContent delay={60}>
          <div className="lp-section-head">
            <p className="lp-section-label">How it works</p>
            <h2 className="lp-h2">From wallet declaration to financial identity.</h2>
          </div>
        </FadeContent>
        <div className="lp-steps">
          {HOW_IT_WORKS.map((s, i) => (
            <FadeContent key={s.num} delay={i * 80}>
              <div className="lp-step">
                <span className="lp-step-num">{s.num}</span>
                <h3>{s.title}</h3>
                <p>{s.body}</p>
              </div>
            </FadeContent>
          ))}
        </div>
      </section>

      {/* ── Ecosystems ── */}
      <section className="lp-section lp-section-alt" id="ecosystems">
        <FadeContent delay={60}>
          <div className="lp-section-head" style={{ marginBottom: "2rem" }}>
            <p className="lp-section-label">Ecosystems</p>
            <h2 className="lp-h2">Financial identity across the agent economy.</h2>
          </div>
          <div className="lp-eco-grid">
            {ECOSYSTEMS.map((eco) => (
              <Link key={eco.name} href={`/registry?eco=${eco.name}`} className="lp-eco-card" style={{ "--eco-color": eco.color } as React.CSSProperties}>
                <span className="lp-eco-dot" style={{ background: eco.color }} />
                <span className="lp-eco-name">{eco.name}</span>
                <span className="lp-eco-arrow">→</span>
              </Link>
            ))}
          </div>
        </FadeContent>
      </section>

      {/* ── $LUCA ── */}
      <LucaTokenSection />

      {/* ── FAQ ── */}
      <section className="lp-section lp-section-alt" id="faq">
        <FadeContent delay={60}>
          <div className="lp-section-head">
            <p className="lp-section-label">FAQ</p>
            <h2 className="lp-h2">Common questions.</h2>
          </div>
        </FadeContent>
        <div className="lp-faq-list">
          {FAQ_ITEMS.map((item) => <FaqItem key={item.q} q={item.q} a={item.a} />)}
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="lp-cta-section">
        <FadeContent>
          <div className="lp-v1-badge" style={{ margin: "0 auto 20px" }}>
            <span className="lp-v1-dot" />
            Registry is live
          </div>
          <h2 className="lp-h2">The agent economy is here.<br />Financial identity is no longer optional.</h2>
          <p>Explore the registry, claim your agent&apos;s profile, or talk to Luca.</p>
          <div style={{ display: "flex", gap: "0.85rem", justifyContent: "center", flexWrap: "wrap", marginTop: "1.5rem" }}>
            <Link href="/registry" className="lp-btn-primary lp-btn-lg">Explore Registry</Link>
            <Link href="/registry#verify" className="lp-btn-ghost lp-btn-lg">Claim a Profile</Link>
            <a href="https://t.me/AskLucaBot" target="_blank" rel="noreferrer" className="lp-btn-ghost lp-btn-lg">Talk to Luca</a>
          </div>
        </FadeContent>
      </section>

      {/* ── Footer ── */}
      <footer className="lp-footer">
        <div className="lp-footer-top">
          <div className="lp-footer-brand">
            <a href="/" className="lp-brand lp-brand-sm"><Logo /></a>
            <p>Financial identity and intelligence for autonomous agents.</p>
            <p className="lp-footer-builder">Built by <a href="https://x.com/danbuildss" target="_blank" rel="noreferrer">@danbuildss</a></p>
            <div className="lp-footer-social">
              {SOCIAL.map((s) => (
                <a key={s.href} href={s.href} target="_blank" rel="noreferrer" aria-label={s.label} className="lp-social-icon">{s.icon}</a>
              ))}
            </div>
          </div>
          <div className="lp-footer-links">
            <div>
              <h4>Product</h4>
              <Link href="/registry">Registry</Link>
              <Link href="/luca">Luca</Link>
              <Link href="/developer">API</Link>
              <Link href="/docs">Docs</Link>
            </div>
            <div>
              <h4>Registry</h4>
              <Link href="/registry">Browse agents</Link>
              <Link href="/registry#verify">Claim profile</Link>
              <Link href="/registry?eco=AEON">AEON</Link>
              <Link href="/registry?eco=BANKR">BANKR</Link>
            </div>
            <div>
              <h4>Community</h4>
              <a href="https://x.com/x402Books" target="_blank" rel="noreferrer">X / Twitter</a>
              <a href="https://t.me/AskLucaBot" target="_blank" rel="noreferrer">@AskLucaBot</a>
              <a href="https://t.me/x402books" target="_blank" rel="noreferrer">Telegram</a>
            </div>
          </div>
        </div>
        <div className="lp-footer-bottom">
          <span>© 2026 x402Books AI. All rights reserved.</span>
          <span>Built on Base · Powered by Claude AI</span>
        </div>
      </footer>
    </div>
  );
}
