import Link from "next/link";

export function SiteFooter() {
  return (
    <footer className="lp-footer">
      <div className="lp-footer-top">
        <div className="lp-footer-brand">
          <a href="/" className="lp-brand lp-brand-sm" style={{ fontWeight: 700, fontSize: "1rem" }}>x402Books</a>
          <p>Financial intelligence for the agent economy.</p>
        </div>
        <div className="lp-footer-links">
          <div>
            <h4>Product</h4>
            <Link href="/registry">Registry</Link>
            <Link href="/leaderboard">Leaderboard</Link>
            <Link href="/research">Research</Link>
            <Link href="/developer">API</Link>
          </div>
          <div>
            <h4>Registry</h4>
            <Link href="/registry">Browse Agents</Link>
            <Link href="/registry#verify">Submit Manifest</Link>
            <Link href="/registry?eco=AEON">AEON Agents</Link>
            <Link href="/registry?eco=BANKR">BANKR Agents</Link>
          </div>
          <div>
            <h4>Community</h4>
            <a href="https://x.com/x402Books" target="_blank" rel="noreferrer">X / Twitter</a>
            <a href="https://t.me/AskLucaBot" target="_blank" rel="noreferrer">@AskLucaBot</a>
            <a href="https://t.me/x402books" target="_blank" rel="noreferrer">Telegram</a>
          </div>
        </div>
      </div>
      <div className="lp-footer-bottom">
        <span>© 2026 x402Books. All rights reserved.</span>
        <span>Financial analysis generated by Luca.</span>
      </div>
    </footer>
  );
}
