import Link from "next/link";
import { LogoMark } from "@/components/logo";

export function SiteFooter() {
  return (
    <footer className="lp-footer">
      <div className="lp-footer-top">
        <div className="lp-footer-brand">
          <a href="/" className="lp-brand lp-brand-sm" aria-label="Zetta">
            <span className="brand" style={{ display: "inline-flex", alignItems: "center", gap: 8 }}>
              <LogoMark size={20} />
              <span style={{ fontWeight: 700, fontSize: "1rem" }}>zetta</span>
            </span>
          </a>
          <p>Financial intelligence for the agent economy.</p>
        </div>
        <div className="lp-footer-links">
          <div>
            <h4>Products</h4>
            <Link href="/registry">Registry</Link>
            <Link href="/leaderboard">Leaderboard</Link>
            <Link href="/b20">B20 Intelligence</Link>
            <Link href="/research">Research</Link>
            <Link href="/developer">API</Link>
            <Link href="/luca">Luca</Link>
          </div>
          <div>
            <h4>Resources</h4>
            <Link href="/methodology">Methodology</Link>
            <Link href="/registry#verify">Submit Agent</Link>
            <Link href="/manifest">Manifest Guide</Link>
            <Link href="/docs">Documentation</Link>
          </div>
          <div>
            <h4>Company</h4>
            <a href="https://x.com/zettaaidotco" target="_blank" rel="noreferrer">X</a>
            <a href="https://t.me/asklucaai" target="_blank" rel="noreferrer">Telegram</a>
            <a href="mailto:contact@zettaai.co">Contact</a>
          </div>
        </div>
      </div>
      <div className="lp-footer-bottom">
        <span>© 2026 Zetta. All rights reserved.</span>
        <span>Financial analysis generated by Luca.</span>
      </div>
    </footer>
  );
}
